import React, { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type Language = 'en' | 'te' | 'hi';

const STORAGE_KEY = '@hc_language';

const EN = {
  // Tabs
  tab_dashboard:  'Dashboard',
  tab_products:   'Products',
  tab_orders:     'Orders',
  tab_analytics:  'Analytics',
  tab_store:      'Store',

  // App Settings modal
  settings_title: 'App Settings',

  settings_notifications:   'Notifications',
  notif_new_orders:         'New Orders',
  notif_new_orders_desc:    'Alert when a buyer places a new order',
  notif_order_updates:      'Order Status Updates',
  notif_order_updates_desc: 'Updates when orders are dispatched or delivered',
  notif_payment:            'Payment Received',
  notif_payment_desc:       'Alert when a payout is transferred to your bank',
  notif_performance:        'Weekly Report',
  notif_performance_desc:   'Summary of your store performance every Monday',
  notif_promos:             'HarvestConnect Updates',
  notif_promos_desc:        'New features, seller programs, and tips',

  settings_display:         'Display',
  display_language:         'Language',
  display_dark_mode:        'Dark Mode',
  display_dark_mode_desc:   'Choose your preferred appearance',
  theme_light:              'Light',
  theme_dark:               'Dark',
  theme_system:             'System',
  coming_soon:              'Coming soon',

  settings_privacy:         'Privacy & Legal',
  privacy_policy:           'Privacy Policy',
  terms_of_service:         'Terms of Service',
  data_permissions:         'Data & Permissions',

  settings_about:           'About',
  about_version:            'App Version',
  about_platform:           'Platform',

  // Dashboard screen
  dash_todays_performance:  "Today's Performance",
  dash_quick_actions:       'Quick Actions',
  dash_add_product:         'Add Product',
  dash_view_orders:         'View Orders',
  dash_request_payout:      'Request Payout',
  dash_analytics:           'Analytics',
  dash_incoming_orders:     'Incoming Orders',
  dash_requires_attention:  'Requires your attention',
  dash_view_all:            'View All ›',
  dash_no_pending_orders:   'No pending orders',
  dash_loading_orders:      'Loading orders...',
  dash_store_health:        'Store Health',
  dash_fulfilment_rate:     'Fulfilment Rate',
  dash_avg_response:        'Avg Response',
  dash_store_rating:        'Store Rating',
  dash_cancel_rate:         'Cancel Rate',
  dash_accept_order:        'Accept Order',
  dash_decline:             'Decline',
  dash_mark_dispatched:     'Mark Dispatched 🚚',
  dash_processing:          'Processing...',
  dash_todays_revenue:      "Today's Revenue",
  dash_new_orders:          'New Orders',
  dash_pending:             'Pending',
  dash_store_views:         'Store Views',
  dash_tip_title:           'Tip: Add harvest photos',
  dash_tip_sub:             'Listings with farm photos get 3× more clicks. Add photos to your top 3 products.',
  dash_good_morning:        'Good morning',
  dash_good_afternoon:      'Good afternoon',
  dash_good_evening:        'Good evening',
  dash_available_payout:    'available for payout',
  dash_t1_settlement:       'T+1 settlement · Tap to request',

  // Payout modal
  payout_title:             'Payout',
  payout_available_label:   'Available for Payout',
  payout_delivered_after:   'after 7% commission',
  payout_delivered_orders:  'delivered order',
  payout_delivered_orders_p:'delivered orders',
  payout_breakdown:         'Breakdown',
  payout_order_revenue:     'Order Revenue',
  payout_commission:        'Platform Commission (7%)',
  payout_you_earn:          'You Earn',
  payout_transfer_to:       'Transfer To',
  payout_verified:          'Verified',
  payout_no_bank:           'No bank account linked. Go to Profile → Bank & Payouts to add one.',
  payout_t1_info:           'Payouts are processed T+1 — funds arrive the next business day after your request.',
  payout_no_orders:         'No delivered orders yet. Amounts become available once buyers confirm delivery.',
  payout_close:             'Close',
  payout_request_btn:       'Request Payout →',
  payout_no_balance:        'No Balance',
  payout_confirm_title:     'Confirm Payout Request',
  payout_bank_required_title: 'Bank Account Required',
  payout_bank_required_msg: 'Add your bank account in Profile → Bank & Payouts before requesting a payout.',
  payout_success_toast:     'Payout requested! Funds arrive by next business day.',
  payout_cancel:            'Cancel',
  payout_request_now:       'Request Now',

  // Orders screen
  orders_new:               'New',
  orders_accepted:          'Accepted',
  orders_dispatched:        'Dispatched',
  orders_delivered:         'Delivered',
  orders_cancelled:         'Cancelled',
  orders_no_orders:         'No orders',
  orders_loading:           'Loading orders...',
  orders_accept_order:      'Accept Order ✓',
  orders_mark_dispatched:   'Mark Dispatched 🚚',
  orders_mark_delivered:    'Mark Delivered ✓',
  orders_decline:           'Decline',
  orders_processing:        'Processing...',
  orders_filter:            'Filter',
  orders_total:             'Total',

  // Analytics screen
  analytics_title:          'Analytics',
  analytics_store_perf:     'Store performance',
  analytics_export:         'Export',
  analytics_loading:        'Loading analytics…',
  analytics_total_revenue:  'Total Revenue',
  analytics_orders:         'Orders',
  analytics_avg_order:      'Avg Order',
  analytics_revenue_breakdown: 'Revenue Breakdown',
  analytics_buyer_insights: 'Buyer Insights',
  analytics_new_buyers:     'New Buyers',
  analytics_returning:      'Returning',
  analytics_repeat_rate:    'Repeat Rate',
  analytics_top_products:   'Top Products',
  analytics_payout_history: 'Payout History',
  analytics_view_all:       'View All ›',
  analytics_no_payouts:     'No payouts yet — completed orders will appear here.',
  analytics_next_payout:    'Next payout: Tonight at 11 PM',
  analytics_orders_settled: 'orders settled',
  analytics_no_pending_payout: 'No pending payout',
  analytics_period_today:   'Today',
  analytics_period_week:    'This Week',
  analytics_period_month:   'This Month',
  analytics_period_all:     'All Time',

  // Products screen
  products_title:           'My Products',
  products_search_placeholder: 'Search products...',
  products_loading:         'Loading products...',
  products_filter_all:      'All',
  products_filter_active:   'Active',
  products_filter_draft:    'Draft',
  products_filter_archived: 'Archived',
  products_filter_low_stock: 'Low Stock',
  products_add:             'Add Product',
  products_in_stock:        'In Stock',
  products_out_of_stock:    'Out of Stock',
  products_low_stock:       'Low',
  products_status_active:   'Active',
  products_status_draft:    'Draft',
  products_status_archived: 'Archived',
  products_no_products_yet: 'No products yet',
  products_no_products_found: 'No products found',
  products_add_new:         'Add a New Product',

  // Store / Profile screen
  store_settings:           'Store Settings',
  store_team_members:       'Team Members',
  store_my_stores:          'My Stores',
  store_bank_payouts:       'Bank & Payouts',
  store_invite_member:      'Invite Member',
  store_loading:            'Loading',

  // Orders screen extras
  orders_header_title:      'Order Management',
  orders_placed:            'Placed',
  orders_empty_sub:         'Orders will appear here when customers place them',
  orders_completed_txt:     'Order completed',
  orders_after_commission:  'earned after 7% commission',
  orders_cancel_reason:     'Reason:',
  orders_filter_hint:       'Filtered by:',
  orders_filter_clear:      'Clear ✕',

  // Products screen extras
  products_selected:         'selected',
  products_listings:         'listings',
  products_sel_hint:         'Tap cards to toggle · Long press to start selection',
  products_cancel_sel:       '✕ Cancel',
  products_cant_load:        'Could not load products',
  products_retry:            'Retry',
  products_empty_add_sub:    'Tap "+ Add" to list your first item on HarvestConnect',
  products_empty_filter_sub: 'Try a different search or filter',
  products_add_cta_sub:      'List your farm produce, handmade goods, or local products',
  products_bulk_activate:    '● Activate',
  products_bulk_archive:     'Archive',
  products_bulk_delete:      '🗑️ Delete',
  products_bulk_select_all:  'Select All',
  products_bulk_clear:       '✕ Clear',
  products_edit:             '✏️ Edit',
  products_reviews:          'reviews',
  products_ships_to:         '🚚 Ships to',

  // Analytics screen extras
  analytics_no_delivered:         'No delivered orders in this period',
  analytics_no_buyers:            'No buyer data for this period',
  analytics_no_sales:             'No sales data for this period',
  analytics_units_sold:           'units sold',
  analytics_payout_transfer:      'will be transferred to your registered bank account',
  analytics_payout_restricted:    'Payout data restricted',
  analytics_payout_restricted_sub:'Only store owners can view payout history and financial details.',

  // Product form modal
  product_form_add_title:           'Add New Product',
  product_form_edit_title:          'Edit Product',
  product_form_listing_under:       'Listing under',
  product_form_name:                'Product Name',
  product_form_name_ph:             'e.g. Organic Turmeric Powder',
  product_form_desc:                'Description',
  product_form_desc_ph:             'Tell buyers what makes this product special — origin, process, quality...',
  product_form_category:            'Category',
  product_form_subcategory:         'Sub-Category',
  product_form_price:               'Price (₹)',
  product_form_orig_price:          'Original / MRP (₹)',
  product_form_orig_price_hint:     'Optional — shown as crossed-out price if higher than selling price',
  product_form_stock:               'Stock Qty',
  product_form_threshold:           'Low Stock Alert Threshold',
  product_form_threshold_hint:      'Get "Low Stock" badge when qty drops below this number',
  product_form_threshold_unit:      'units',
  product_form_unit:                'Unit',
  product_form_unit_ph:             'Or type custom unit...',
  product_form_delivery:            'Delivery Scope',
  product_form_images:              'Product Images',
  product_form_pick_device:         '📷 Pick from device',
  product_form_paste_url:           'Or paste image URL...',
  product_form_add_url:             'Add',
  product_form_status:              'Listing Status',
  product_form_status_active_desc:  'Active — visible to buyers',
  product_form_status_draft_desc:   'Draft — hidden from buyers',
  product_form_draft:               'Draft',
  product_form_active:              'Active',
  product_form_handmade:            'Handmade / Artisan',
  product_form_handmade_sub:        'Made by hand or local craft',
  product_form_save:                '💾 Save Changes',
  product_form_add_btn:             '＋ Add Product',
  product_form_err_name:            'Product name is required.',
  product_form_err_price:           'Enter a valid price in ₹.',
  product_form_err_stock:           'Enter a valid stock quantity (0 or more).',
  product_form_img_limit:           'You can add up to 5 images.',

  // Store switcher
  switcher_title:        'Switch Store',
  switcher_managing:     'You are managing',
  switcher_stores:       'stores',
  switcher_products:     'products',
  switcher_members:      'members',
  switcher_orders_today: 'orders today',
  switcher_create_store: 'Create New Store',
  switcher_create_sub:   'Set up another storefront on HarvestConnect',
  switcher_created_msg:  'created! Upload KYC to get verified.',

  // Create store modal
  create_store_title:          'Create New Store',
  create_store_subtitle:       'Your store will be visible after admin verification',
  create_store_type:           'Store Type',
  create_store_name:           'Store Name',
  create_store_name_ph:        'e.g. Ravi Organic Farm',
  create_store_phone:          'Mobile Number',
  create_store_phone_hint:     '10-digit Indian number · used as store contact',
  create_store_phone_ph:       'e.g. 9876543210',
  create_store_location:       'Location',
  create_store_location_hint:  'Display name shown to buyers',
  create_store_location_ph:    'e.g. Nizamabad, Telangana',
  create_store_pincode:        'Pincode',
  create_store_pincode_hint:   'Used to set delivery coordinates',
  create_store_pincode_ph:     '6-digit pincode',
  create_store_zones:          'Delivery Zones',
  create_store_desc:           'Description',
  create_store_desc_hint:      'Optional · shown on your store profile',
  create_store_desc_ph:        'Tell buyers what you sell and what makes your store special…',
  create_store_fssai:          'FSSAI License Number',
  create_store_fssai_hint:     'Optional · required for food sellers',
  create_store_fssai_ph:       '14-digit FSSAI number',
  create_store_btn:            'Create Store',
  create_store_note:           'New stores start as unverified. Upload KYC documents to get the Verified badge.',
  create_store_err_name:       'Store name is required',
  create_store_err_phone:      'Enter a valid 10-digit Indian mobile number',
  create_store_err_location:   'Location is required (e.g. Nizamabad, Telangana)',
  create_store_err_pincode:    'Enter a valid 6-digit pincode',
  create_store_err_zones:      'Select at least one delivery zone',

  // Invite member modal
  invite_title:             'Invite Team Member',
  invite_name:              'Full Name',
  invite_name_ph:           'e.g. Ramesh Kumar',
  invite_phone:             'Mobile Number',
  invite_phone_ph:          '+91 98765 43210',
  invite_role:              'Role',
  invite_role_manager:      'Manager',
  invite_role_manager_desc: 'Can edit products & view analytics',
  invite_role_staff:        'Staff',
  invite_role_staff_desc:   'Can process orders only',
  invite_hint:              "They'll receive an SMS invite to join your store on HarvestConnect.",
  invite_sending:           'Sending...',
  invite_send:              'Send Invite',

  // Profile / Store screen extras
  profile_stat_products:     'Products',
  profile_stat_orders:       'Total Orders',
  profile_stat_rating:       'Rating',
  profile_stat_gmv:          'Total GMV',
  profile_identity:          'Identity & Compliance',
  profile_identity_sub:      'Aadhaar · FSSAI · Bank Account',
  profile_payout_account:    'Payout Account',
  profile_bank_not_setup:    'Not set up yet',
  profile_change_bank:       'Change',
  profile_add_bank:          'Add',
  profile_delivery_coverage: 'Delivery Coverage',
  profile_no_zones:          'No delivery zones configured',
  profile_edit_coverage:     'Edit ›',
  profile_fssai_title:       'FSSAI License',
  profile_fssai_not_provided:'Not provided',
  profile_fssai_active:      'Active',
  profile_fssai_pending:     'Pending',
  profile_switch:            'Switch ›',
  profile_viewing:           'Viewing',
  profile_store_live:        '● Live',
  profile_store_offline:     '○ Offline',
  profile_member_active:     'Active',
  profile_member_pending:    'Pending',
  profile_you:               '(you)',
  profile_invited:           'Invited',
  profile_joined:            'Joined',
  profile_logout_btn:        '🚪  Logout',
  profile_logout_title:      'Log Out',
  profile_logout_msg:        'Are you sure you want to log out of HarvestConnect Seller?',
  profile_logout_cancel:     'Cancel',
  profile_logout_confirm:    'Log Out',
  profile_tier_title:        'Gold Seller · HarvestConnect',
  profile_tier_sub:          'Top 5% of sellers · Eligible for featured placement · Priority support',
  profile_invite_count:      'Store Invitation',
  profile_invite_count_p:    'Store Invitations',
  profile_invite_sub:        'Tap to review and accept',
  menu_store_settings_desc:  'Store name, photo, description, category',
  menu_my_products:          'My Products',
  menu_my_products_desc:     'Manage your product catalogue',
  menu_order_history:        'Order History',
  menu_order_history_desc:   'All completed and cancelled orders',
  menu_bank_payouts_desc:    'Manage payout account · T+1 settlement',
  menu_tx_history:           'Transaction History',
  menu_tx_history_desc:      'All credits, debits, and commissions',
  menu_delivery_zones:       'Delivery Zones',
  menu_delivery_zones_desc:  'Mandal, district, state coverage areas',
  menu_kyc:                  'KYC & Documents',
  menu_kyc_desc:             'Aadhaar, FSSAI, bank verification',
  menu_promotions:           'Promotions & Offers',
  menu_promotions_desc:      'Create discounts and bundle deals',
  menu_share_store:          'Share My Store',
  menu_share_store_desc:     'Share your storefront link',
  menu_reviews:              'Reviews & Ratings',
  menu_reviews_desc:         '4.8 avg · 342 reviews',
  menu_help:                 'Help & Support',
  menu_help_desc:            'FAQs, contact, seller guides',
  menu_app_settings:         'App Settings',
  menu_app_settings_desc:    'Notifications, language, privacy',
  menu_social_handles:       'Social Media',
  menu_social_handles_desc:  'Instagram, Facebook, WhatsApp & more',

  // Order detail modal
  order_detail_placed:              'Placed',
  order_detail_timeline_placed:     'Order Placed',
  order_detail_timeline_accepted:   'Accepted',
  order_detail_timeline_dispatched: 'Dispatched',
  order_detail_timeline_delivered:  'Delivered',
  order_detail_cancelled:           'Cancelled',
  order_detail_refund_init:         'Refund Initiated',
  order_detail_refunded:            'Refunded',
  order_detail_buyer:               'BUYER',
  order_detail_call:                'Call',
  order_detail_items:               'ITEMS',
  order_detail_payment:             'PAYMENT SUMMARY',
  order_detail_subtotal:            'Subtotal',
  order_detail_delivery_fee:        'Delivery fee',
  order_detail_discount:            'Discount',
  order_detail_total:               'Total',
  order_detail_pay_method:          'Payment',
  order_detail_tracking:            'TRACKING',
  order_detail_est_delivery:        'Est. delivery:',
  order_detail_decline:             'Decline',
  order_detail_processing:          'Processing...',

  // Order filter modal
  filter_orders_title:  'Filter Orders',
  filter_payment_label: 'PAYMENT METHOD',
  filter_all:           'All',
  filter_upi:           'UPI',
  filter_cod:           'COD',
  filter_card:          'Card',
  filter_wallet:        'Wallet',
  filter_clear:         'Clear filters',
  filter_done:          'Done',
  filter_hint_prefix:   'Filtered by:',
  filter_clear_x:       'Clear ✕',

  // Decline reason modal
  decline_title:        'Decline Order',
  decline_reason_label: 'Reason for declining *',
  decline_placeholder:  'e.g. Item out of stock, unable to deliver to this location...',
  decline_hint:         'The buyer will be notified with this reason.',
  decline_cancel:       'Cancel',
  decline_confirm:      'Decline Order',
  decline_loading:      'Declining...',

  // Product detail modal
  product_detail_title:     'Product Details',
  product_detail_no_images: 'No images added',
  product_detail_desc:      'Description',
  product_detail_rating:    'Rating',
  product_detail_reviews:   'Reviews',
  product_detail_listed:    'Listed on',
  product_detail_to_draft:  '○ Move to Draft',
  product_detail_make_live: '● Make Live',
  product_detail_edit:      '✏️ Edit Product',
  product_detail_live:      '● Live',
  product_detail_draft:     '○ Draft',
  product_detail_archived_lbl:'✕ Archived',
  product_detail_handmade:  '🪡 Handmade',
  product_detail_verified:  '✓ Verified',
  product_detail_out_stock: 'Out of Stock',
  product_detail_low_stock: 'Low Stock',
  product_detail_in_stock:  'In Stock',
  product_detail_units:     'units',
  product_detail_left:      'left',
  product_detail_alert:     'alert at',

  // Help & Support modal
  help_title:         'Help & Support',
  help_hint:          'Browse common questions below or contact our seller support team directly.',
  help_faqs:          'Frequently Asked Questions',
  help_contact:       'Still Need Help?',
  help_call:          'Call Support',
  help_call_hours:    'Mon–Sat, 9 AM – 6 PM',
  help_whatsapp:      'WhatsApp',
  help_whatsapp_sub:  'Quick replies via chat',
  help_email:         'Email Us',
  help_email_sub:     'seller-support@harvestconnect.in',
  help_guide:         '📖  Seller Guide & Best Practices',
  help_guide_sub:     'Tips on pricing, photography, and growing your sales',
  help_faq_q1: 'How do I accept a new order?',
  help_faq_a1: 'Go to the Orders tab. New orders appear at the top under "New". Tap the order card and press "Accept" — the order moves to Accepted and the buyer is notified.',
  help_faq_q2: 'When and how do I get paid?',
  help_faq_a2: 'Payments are settled T+1 (the next business day after delivery confirmation). Funds are transferred directly to your registered bank account. You can track payouts in the Analytics screen.',
  help_faq_q3: 'How do I add or edit a product?',
  help_faq_a3: 'Go to the Products tab. Tap "＋ Add Product" to create a new listing, or tap any existing product to edit it. You can update price, stock, images, and description at any time.',
  help_faq_q4: 'What commission does HarvestConnect charge?',
  help_faq_a4: 'HarvestConnect charges 7% commission on each successfully delivered order. You earn 93% of the order value. Commission is deducted before the payout is transferred.',
  help_faq_q5: 'How do I get my store verified?',
  help_faq_a5: 'Upload your FSSAI license number and supporting documents via Profile → KYC & Documents. Our compliance team reviews submissions within 48 hours on business days.',
  help_faq_q6: 'How do I cancel or decline an order?',
  help_faq_a6: 'For new (unaccepted) orders: tap the order and press "Decline", then enter a reason. For accepted orders that cannot be fulfilled, please contact support directly — we will assist with buyer communication.',
  help_faq_q7: 'How do I update my delivery zones?',
  help_faq_a7: 'Go to Profile → Delivery Zones (or tap "Edit ›" in the Delivery Coverage card). Select the zones you can serve and save. Changes take effect immediately for new buyer searches.',
  help_faq_q8: 'Can I have multiple stores?',
  help_faq_a8: 'Yes. Tap the store icon at the top of any screen to open the Store Switcher. Tap "Create New Store" to set up an additional storefront — each store has its own products, orders, and team.',

  // Transaction history modal
  tx_title:             'Transaction History',
  tx_total_credited:    'Total Credited',
  tx_total_debited:     'Total Debited',
  tx_net_balance:       'Net Balance',
  tx_filter_all:        'All',
  tx_filter_credits:    'Credits',
  tx_filter_debits:     'Debits',
  tx_filter_commission: 'Commission',
  tx_empty_title:       'No transactions yet',
  tx_empty_all:         'Completed orders will appear here as credits and commissions.',
  tx_empty_filter:      'No transactions found.',
  tx_type_credit:       'Credit',
  tx_type_debit:        'Debit',
  tx_type_commission:   'Commission',

  // Delivery zones modal
  zones_title:           'Delivery Zones',
  zones_hint:            "Select all areas you can deliver to. Buyers outside your selected zones won't see your listings.",
  zones_desc_mandal:     'Nearby villages and towns within your mandal',
  zones_desc_district:   'All areas within your district',
  zones_desc_state:      'Anywhere within Telangana & Andhra Pradesh',
  zones_desc_national:   'Pan-India delivery via courier partner',
  zones_saving:          'Saving…',
  zones_save_pre:        'Save ·',
  zones_zone:            'zone',
  zones_zones:           'zones',

  // Edit store modal
  edit_store_title:        'Edit Store',
  edit_store_name:         'Store Name',
  edit_store_name_ph:      'e.g. Desi Dairy Armoor',
  edit_store_desc:         'Description',
  edit_store_desc_ph:      'Tell buyers about your store, your produce, your story…',
  edit_store_location:     'Location',
  edit_store_location_ph:  'e.g. Nizamabad, Telangana',
  edit_store_address:      'Store Address',
  edit_store_address_ph:   'Street, area, landmark — shown on your store profile',
  edit_store_social:       'Social Media Handles',
  edit_store_instagram:    'Instagram',
  edit_store_instagram_ph: 'yourhandle',
  edit_store_facebook:     'Facebook',
  edit_store_facebook_ph:  'facebook.com/yourpage',
  edit_store_whatsapp:     'WhatsApp Business',
  edit_store_whatsapp_ph:  '+91 98765 43210',
  edit_store_website:      'Website',
  edit_store_website_ph:   'https://yourwebsite.com',
  edit_store_youtube:      'YouTube Channel',
  edit_store_youtube_ph:   'youtube.com/@yourchannel',
  edit_store_type:         'Store Type',
  edit_store_status:       'Store Status',
  edit_store_live_desc:    'Visible · accepting orders',
  edit_store_offline_desc: 'Hidden from buyers',
  edit_store_saving:       'Saving…',
  edit_store_save:         'Save Changes',

  // Bank account modal
  bank_title_add:        'Add Bank Account',
  bank_title_update:     'Update Bank Account',
  bank_subtitle:         'Payouts are settled T+1 to this account',
  bank_holder_name:      'Account Holder Name',
  bank_holder_name_ph:   'As per bank records',
  bank_account_no:       'Account Number',
  bank_account_no_ph:    'Enter full account number',
  bank_account_reenter:  're-enter to change',
  bank_ifsc:             'IFSC Code',
  bank_ifsc_ph:          'e.g. HDFC0001234',
  bank_name:             'Bank Name',
  bank_name_ph:          'e.g. HDFC Bank',
  bank_upi:              'UPI ID',
  bank_upi_hint:         'Optional — for faster settlements',
  bank_upi_ph:           'e.g. name@hdfcbank',
  bank_save_btn:         'Save Account',
  bank_update_btn:       'Update Account',
  bank_err_holder:       'Account holder name is required',
  bank_err_account:      'Account number must be 9–18 digits (numbers only)',
  bank_err_ifsc:         'Invalid IFSC code (e.g. HDFC0001234)',
  bank_err_bank_name:    'Bank name is required',
  bank_err_save:         'Failed to save. Please try again.',

  // KYC & documents modal
  kyc_title:             'KYC & Documents',
  kyc_verified_title:    'KYC Verified',
  kyc_pending_title:     'Verification Pending',
  kyc_verified_sub:      'Your account is verified and fully eligible for payouts.',
  kyc_pending_sub:       'Submit your FSSAI number and supporting documents. Admin reviews within 48 hours.',
  kyc_fssai_label:       'FSSAI License Number',
  kyc_fssai_hint:        '14-digit number from your FSSAI food license certificate  e.g. 36214500000001',
  kyc_docs_label:        'Supporting Documents',
  kyc_no_docs:           'No documents uploaded yet',
  kyc_doc_url_ph:        'Paste document URL (Google Drive, Dropbox…)',
  kyc_doc_add:           'Add',
  kyc_upload_hint:       'Camera & gallery upload coming soon. For now, host your document on Google Drive or Dropbox and paste the shareable link above.',
  kyc_accepted_title:    'Accepted Documents',
  kyc_accepted_1:        'Aadhaar Card (both sides)',
  kyc_accepted_2:        'PAN Card',
  kyc_accepted_3:        'FSSAI License Certificate',
  kyc_accepted_4:        'Bank account statement / passbook',
  kyc_accepted_5:        'GST Certificate (if applicable)',
  kyc_saving:            'Saving…',
  kyc_save:              'Save',

  // Promotions modal
  promo_title:           'Promotions & Offers',
  promo_new_form_title:  'New Promotion',
  promo_type_label:      'Promotion Type',
  promo_type_percent:    '% Off',
  promo_type_flat:       'Flat ₹ Off',
  promo_type_free_del:   'Free Delivery',
  promo_disc_pct:        'Discount Percentage *',
  promo_disc_flat:       'Discount Amount *',
  promo_min_order:       'Min. Order Amount (optional)',
  promo_valid_for:       'Valid For',
  promo_days:            'days',
  promo_1_month:         '1 month',
  promo_create:          'Create',
  promo_new_btn:         'Create New Promotion',
  promo_new_sub:         'Discounts, free delivery, and more',
  promo_empty_title:     'No active promotions',
  promo_empty_sub:       'Create a discount or offer to attract more buyers and boost your sales.',
  promo_min_order_label: 'Min. order ₹',
  promo_valid_pre:       'Valid',
  promo_active:          'Active',
  promo_paused:          'Paused',
  promo_pause:           'Pause',
  promo_resume:          'Resume',
  promo_delete:          'Delete',
  promo_off:             'Off',
  promo_created_toast:   'Promotion created!',
  promo_removed_toast:   'Promotion removed.',
  promo_sync_note:       'Promotions are session-only for now. Persistent management will be available once the promotions service is live.',

  // Kirana business model toggle
  create_store_business_model:    'Business Model',
  create_store_retail:            'Retail',
  create_store_retail_sub:        'Sells to consumers',
  create_store_wholesale:         'Wholesale',
  create_store_wholesale_sub:     'Bulk to shops / resellers',

  // Custom delivery area (create-store)
  create_store_custom_area_on:    '✕ Custom Area',
  create_store_custom_area_off:   '+ Custom Area',
  create_store_custom_area_title: 'Custom Delivery Area Selected',
  create_store_custom_area_desc:  'You can define specific mandals, districts, pincodes and states from Store Settings after creation.',

  // Duplicate store type warning
  create_store_dup_title_prefix:  'You already have a',
  create_store_dup_title_suffix:  'store',
  create_store_dup_desc:          'Creating another one is allowed, but consider using your existing store instead. Are you sure?',
  create_store_dup_confirm:       'Create Anyway',

  // Product form — new fields
  product_form_moq_label:         'Minimum Order Quantity (MOQ)',
  product_form_custom_area:       'Custom Area',
  product_form_custom_area_title: 'Custom Delivery Area',
  product_form_custom_area_desc:  "Ships to your store's custom delivery area",
};

const TE: typeof EN = {
  // Tabs
  tab_dashboard:  'డాష్‌బోర్డ్',
  tab_products:   'ఉత్పత్తులు',
  tab_orders:     'ఆర్డర్లు',
  tab_analytics:  'విశ్లేషణలు',
  tab_store:      'స్టోర్',

  // App Settings modal
  settings_title: 'యాప్ సెట్టింగ్‌లు',

  settings_notifications:   'నోటిఫికేషన్లు',
  notif_new_orders:         'కొత్త ఆర్డర్లు',
  notif_new_orders_desc:    'కొనుగోలుదారు కొత్త ఆర్డర్ చేసినప్పుడు హెచ్చరిక',
  notif_order_updates:      'ఆర్డర్ స్థితి నవీకరణలు',
  notif_order_updates_desc: 'ఆర్డర్లు పంపబడినప్పుడు లేదా డెలివరీ అయినప్పుడు నవీకరణలు',
  notif_payment:            'చెల్లింపు అందింది',
  notif_payment_desc:       'మీ బ్యాంకుకు చెల్లింపు బదిలీ అయినప్పుడు హెచ్చరిక',
  notif_performance:        'వారపు నివేదిక',
  notif_performance_desc:   'ప్రతి సోమవారం మీ స్టోర్ పనితీరు సారాంశం',
  notif_promos:             'హార్వెస్ట్‌కనెక్ట్ నవీకరణలు',
  notif_promos_desc:        'కొత్త ఫీచర్లు, విక్రేత కార్యక్రమాలు మరియు చిట్కాలు',

  settings_display:         'ప్రదర్శన',
  display_language:         'భాష',
  display_dark_mode:        'డార్క్ మోడ్',
  display_dark_mode_desc:   'మీకు నచ్చిన రూపాన్ని ఎంచుకోండి',
  theme_light:              'లైట్',
  theme_dark:               'డార్క్',
  theme_system:             'సిస్టమ్',
  coming_soon:              'త్వరలో రానుంది',

  settings_privacy:         'గోప్యత & చట్టపరమైనవి',
  privacy_policy:           'గోప్యతా విధానం',
  terms_of_service:         'సేవా నిబంధనలు',
  data_permissions:         'డేటా & అనుమతులు',

  settings_about:           'గురించి',
  about_version:            'యాప్ వెర్షన్',
  about_platform:           'ప్లాట్‌ఫాం',

  // Dashboard screen
  dash_todays_performance:  'నేటి పనితీరు',
  dash_quick_actions:       'శీఘ్ర చర్యలు',
  dash_add_product:         'ఉత్పత్తి జోడించు',
  dash_view_orders:         'ఆర్డర్లు చూడు',
  dash_request_payout:      'చెల్లింపు అభ్యర్థించు',
  dash_analytics:           'విశ్లేషణలు',
  dash_incoming_orders:     'వస్తున్న ఆర్డర్లు',
  dash_requires_attention:  'మీ దృష్టి అవసరం',
  dash_view_all:            'అన్నీ చూడు ›',
  dash_no_pending_orders:   'పెండింగ్ ఆర్డర్లు లేవు',
  dash_loading_orders:      'లోడవుతోంది...',
  dash_store_health:        'స్టోర్ ఆరోగ్యం',
  dash_fulfilment_rate:     'నెరవేర్పు రేటు',
  dash_avg_response:        'సగటు స్పందన',
  dash_store_rating:        'స్టోర్ రేటింగ్',
  dash_cancel_rate:         'రద్దు రేటు',
  dash_accept_order:        'ఆర్డర్ స్వీకరించు',
  dash_decline:             'తిరస్కరించు',
  dash_mark_dispatched:     'పంపబడినట్లు గుర్తించు 🚚',
  dash_processing:          'ప్రాసెస్ అవుతోంది...',
  dash_todays_revenue:      'నేటి ఆదాయం',
  dash_new_orders:          'కొత్త ఆర్డర్లు',
  dash_pending:             'పెండింగ్',
  dash_store_views:         'స్టోర్ వీక్షణలు',
  dash_tip_title:           'చిట్కా: పంట ఫోటోలు జోడించండి',
  dash_tip_sub:             'పొలం ఫోటోలతో లిస్టింగ్‌లు 3× ఎక్కువ క్లిక్‌లు పొందుతాయి. మీ టాప్ 3 ఉత్పత్తులకు ఫోటోలు జోడించండి.',
  dash_good_morning:        'శుభోదయం',
  dash_good_afternoon:      'శుభ మధ్యాహ్నం',
  dash_good_evening:        'శుభ సాయంత్రం',
  dash_available_payout:    'చెల్లింపుకు అందుబాటులో ఉంది',
  dash_t1_settlement:       'T+1 పరిష్కారం · అభ్యర్థించడానికి నొక్కండి',

  // Payout modal
  payout_title:             'చెల్లింపు',
  payout_available_label:   'చెల్లింపుకు అందుబాటులో',
  payout_delivered_after:   '7% కమీషన్ తర్వాత',
  payout_delivered_orders:  'డెలివరీ ఆర్డర్',
  payout_delivered_orders_p:'డెలివరీ ఆర్డర్లు',
  payout_breakdown:         'వివరణ',
  payout_order_revenue:     'ఆర్డర్ ఆదాయం',
  payout_commission:        'ప్లాట్‌ఫాం కమీషన్ (7%)',
  payout_you_earn:          'మీరు సంపాదించేది',
  payout_transfer_to:       'బదిలీ చేయడానికి',
  payout_verified:          'నిర్ధారించబడింది ✓',
  payout_no_bank:           'బ్యాంక్ ఖాతా లింక్ లేదు. జోడించడానికి ప్రొఫైల్ → బ్యాంక్ & చెల్లింపులకు వెళ్ళండి.',
  payout_t1_info:           'చెల్లింపులు T+1లో ప్రాసెస్ అవుతాయి — అభ్యర్థన తర్వాత తదుపరి వ్యాపార దినాన నిధులు వస్తాయి.',
  payout_no_orders:         'ఇంకా డెలివరీ ఆర్డర్లు లేవు. కొనుగోలుదారులు నిర్ధారించిన తర్వాత మొత్తాలు అందుబాటులో వస్తాయి.',
  payout_close:             'మూసివేయి',
  payout_request_btn:       'చెల్లింపు అభ్యర్థించు →',
  payout_no_balance:        'బ్యాలెన్స్ లేదు',
  payout_confirm_title:     'చెల్లింపు అభ్యర్థన నిర్ధారించండి',
  payout_bank_required_title: 'బ్యాంక్ ఖాతా అవసరం',
  payout_bank_required_msg: 'అభ్యర్థించే ముందు ప్రొఫైల్ → బ్యాంక్ & చెల్లింపులలో బ్యాంక్ ఖాతా జోడించండి.',
  payout_success_toast:     'చెల్లింపు అభ్యర్థించబడింది! తదుపరి వ్యాపార దినాన నిధులు వస్తాయి.',
  payout_cancel:            'రద్దు చేయి',
  payout_request_now:       'ఇప్పుడు అభ్యర్థించు',

  // Orders screen
  orders_new:               'కొత్త',
  orders_accepted:          'స్వీకరించబడింది',
  orders_dispatched:        'పంపబడింది',
  orders_delivered:         'డెలివరీ అయింది',
  orders_cancelled:         'రద్దు చేయబడింది',
  orders_no_orders:         'ఆర్డర్లు లేవు',
  orders_loading:           'లోడవుతోంది...',
  orders_accept_order:      'ఆర్డర్ స్వీకరించు ✓',
  orders_mark_dispatched:   'పంపబడినట్లు గుర్తించు 🚚',
  orders_mark_delivered:    'డెలివరీ అయినట్లు గుర్తించు ✓',
  orders_decline:           'తిరస్కరించు',
  orders_processing:        'ప్రాసెస్ అవుతోంది...',
  orders_filter:            'ఫిల్టర్',
  orders_total:             'మొత్తం',

  // Analytics screen
  analytics_title:          'విశ్లేషణలు',
  analytics_store_perf:     'స్టోర్ పనితీరు',
  analytics_export:         'ఎగుమతి',
  analytics_loading:        'లోడవుతోంది…',
  analytics_total_revenue:  'మొత్తం ఆదాయం',
  analytics_orders:         'ఆర్డర్లు',
  analytics_avg_order:      'సగటు ఆర్డర్',
  analytics_revenue_breakdown: 'ఆదాయ విభజన',
  analytics_buyer_insights: 'కొనుగోలుదారు అంతర్దృష్టులు',
  analytics_new_buyers:     'కొత్త కొనుగోలుదారులు',
  analytics_returning:      'తిరిగి వచ్చిన',
  analytics_repeat_rate:    'పునరావృత రేటు',
  analytics_top_products:   'అగ్ర ఉత్పత్తులు',
  analytics_payout_history: 'చెల్లింపు చరిత్ర',
  analytics_view_all:       'అన్నీ చూడు ›',
  analytics_no_payouts:     'ఇంకా చెల్లింపులు లేవు — పూర్తయిన ఆర్డర్లు ఇక్కడ కనిపిస్తాయి.',
  analytics_next_payout:    'తదుపరి చెల్లింపు: నేటి రాత్రి 11 గంటలకు',
  analytics_orders_settled: 'ఆర్డర్లు పరిష్కారమయ్యాయి',
  analytics_no_pending_payout: 'పెండింగ్ చెల్లింపు లేదు',
  analytics_period_today:   'నేడు',
  analytics_period_week:    'ఈ వారం',
  analytics_period_month:   'ఈ నెల',
  analytics_period_all:     'అన్ని కాలం',

  // Products screen
  products_title:           'నా ఉత్పత్తులు',
  products_search_placeholder: 'ఉత్పత్తులు వెతకండి...',
  products_loading:         'లోడవుతోంది...',
  products_filter_all:      'అన్నీ',
  products_filter_active:   'చురుకుగా',
  products_filter_draft:    'డ్రాఫ్ట్',
  products_filter_archived: 'ఆర్కైవ్ చేయబడింది',
  products_filter_low_stock: 'తక్కువ స్టాక్',
  products_add:             'ఉత్పత్తి జోడించు',
  products_in_stock:        'స్టాక్‌లో ఉంది',
  products_out_of_stock:    'స్టాక్ అయిపోయింది',
  products_low_stock:       'తక్కువ',
  products_status_active:   'చురుకుగా',
  products_status_draft:    'డ్రాఫ్ట్',
  products_status_archived: 'ఆర్కైవ్',
  products_no_products_yet: 'ఇంకా ఉత్పత్తులు లేవు',
  products_no_products_found: 'ఉత్పత్తులు కనుగొనబడలేదు',
  products_add_new:         'కొత్త ఉత్పత్తి జోడించు',

  // Store / Profile screen
  store_settings:           'స్టోర్ సెట్టింగ్‌లు',
  store_team_members:       'బృంద సభ్యులు',
  store_my_stores:          'నా స్టోర్‌లు',
  store_bank_payouts:       'బ్యాంక్ & చెల్లింపులు',
  store_invite_member:      'సభ్యుడిని ఆహ్వానించు',
  store_loading:            'లోడవుతోంది',

  // Orders screen extras
  orders_header_title:      'ఆర్డర్ నిర్వహణ',
  orders_placed:            'ఉంచబడింది',
  orders_empty_sub:         'కస్టమర్లు ఆర్డర్ చేసినప్పుడు ఇక్కడ కనిపిస్తాయి',
  orders_completed_txt:     'ఆర్డర్ పూర్తయింది',
  orders_after_commission:  '7% కమీషన్ తర్వాత సంపాదించారు',
  orders_cancel_reason:     'కారణం:',
  orders_filter_hint:       'ఫిల్టర్ చేయబడింది:',
  orders_filter_clear:      'క్లియర్ ✕',

  // Products screen extras
  products_selected:         'ఎంపిక చేయబడింది',
  products_listings:         'లిస్టింగ్‌లు',
  products_sel_hint:         'టాగిల్ చేయడానికి కార్డులపై నొక్కండి · ఎంపిక ప్రారంభించడానికి దీర్ఘంగా నొక్కండి',
  products_cancel_sel:       '✕ రద్దు చేయి',
  products_cant_load:        'ఉత్పత్తులు లోడ్ కాలేదు',
  products_retry:            'మళ్ళీ ప్రయత్నించు',
  products_empty_add_sub:    '"+ జోడించు" నొక్కి మీ మొదటి ఉత్పత్తిని లిస్ట్ చేయండి',
  products_empty_filter_sub: 'వేరే శోధన లేదా ఫిల్టర్ ప్రయత్నించండి',
  products_add_cta_sub:      'మీ వ్యవసాయ ఉత్పత్తులు, హస్తకళలు లేదా స్థానిక ఉత్పత్తులను లిస్ట్ చేయండి',
  products_bulk_activate:    '● సక్రియం చేయి',
  products_bulk_archive:     'ఆర్కైవ్ చేయి',
  products_bulk_delete:      '🗑️ తొలగించు',
  products_bulk_select_all:  'అన్నీ ఎంచుకో',
  products_bulk_clear:       '✕ క్లియర్',
  products_edit:             '✏️ సవరించు',
  products_reviews:          'సమీక్షలు',
  products_ships_to:         '🚚 డెలివరీ:',

  // Analytics screen extras
  analytics_no_delivered:         'ఈ కాలంలో డెలివరీ ఆర్డర్లు లేవు',
  analytics_no_buyers:            'ఈ కాలంలో కొనుగోలుదారు డేటా లేదు',
  analytics_no_sales:             'ఈ కాలంలో విక్రయ డేటా లేదు',
  analytics_units_sold:           'యూనిట్లు అమ్మబడ్డాయి',
  analytics_payout_transfer:      'మీ నమోదిత బ్యాంక్ ఖాతాకు బదిలీ చేయబడుతుంది',
  analytics_payout_restricted:    'చెల్లింపు డేటా పరిమితం',
  analytics_payout_restricted_sub:'స్టోర్ యజమానులు మాత్రమే చెల్లింపు చరిత్ర మరియు ఆర్థిక వివరాలు చూడగలరు.',

  // Product form modal
  product_form_add_title:           'కొత్త ఉత్పత్తి జోడించు',
  product_form_edit_title:          'ఉత్పత్తి సవరించు',
  product_form_listing_under:       'లిస్టింగ్ అండర్',
  product_form_name:                'ఉత్పత్తి పేరు',
  product_form_name_ph:             'ఉదా. సేంద్రీయ పసుపు పొడి',
  product_form_desc:                'వివరణ',
  product_form_desc_ph:             'ఈ ఉత్పత్తిని ప్రత్యేకంగా చేసేది ఏమిటో చెప్పండి — మూలం, ప్రక్రియ, నాణ్యత...',
  product_form_category:            'వర్గం',
  product_form_subcategory:         'ఉప-వర్గం',
  product_form_price:               'ధర (₹)',
  product_form_orig_price:          'అసల్ / MRP (₹)',
  product_form_orig_price_hint:     'ఐచ్ఛికం — అమ్మకపు ధర కంటే ఎక్కువైతే అడ్డంగా చూపబడుతుంది',
  product_form_stock:               'స్టాక్ పరిమాణం',
  product_form_threshold:           'తక్కువ స్టాక్ హెచ్చరిక పరిమితి',
  product_form_threshold_hint:      'పరిమాణం ఈ సంఖ్య కంటే తక్కువైనప్పుడు "తక్కువ స్టాక్" బ్యాడ్జ్ వస్తుంది',
  product_form_threshold_unit:      'యూనిట్లు',
  product_form_unit:                'యూనిట్',
  product_form_unit_ph:             'లేదా కస్టమ్ యూనిట్ టైప్ చేయండి...',
  product_form_delivery:            'డెలివరీ పరిధి',
  product_form_images:              'ఉత్పత్తి చిత్రాలు',
  product_form_pick_device:         '📷 పరికరం నుండి ఎంచుకో',
  product_form_paste_url:           'లేదా చిత్ర URL పేస్ట్ చేయండి...',
  product_form_add_url:             'జోడించు',
  product_form_status:              'లిస్టింగ్ స్థితి',
  product_form_status_active_desc:  'యాక్టివ్ — కొనుగోలుదారులకు కనిపిస్తుంది',
  product_form_status_draft_desc:   'డ్రాఫ్ట్ — కొనుగోలుదారులకు దాచబడింది',
  product_form_draft:               'డ్రాఫ్ట్',
  product_form_active:              'యాక్టివ్',
  product_form_handmade:            'హస్తకళ / కళాకారుడి ఉత్పత్తి',
  product_form_handmade_sub:        'చేతితో లేదా స్థానిక కళతో తయారైంది',
  product_form_save:                '💾 మార్పులు సేవ్ చేయి',
  product_form_add_btn:             '＋ ఉత్పత్తి జోడించు',
  product_form_err_name:            'ఉత్పత్తి పేరు తప్పనిసరి.',
  product_form_err_price:           'సరైన ధరను ₹లో నమోదు చేయండి.',
  product_form_err_stock:           'సరైన స్టాక్ పరిమాణాన్ని నమోదు చేయండి (0 లేదా ఎక్కువ).',
  product_form_img_limit:           '5 చిత్రాల వరకు మాత్రమే జోడించవచ్చు.',

  // Store switcher
  switcher_title:        'స్టోర్ మార్చు',
  switcher_managing:     'మీరు',
  switcher_stores:       'స్టోర్లు నిర్వహిస్తున్నారు',
  switcher_products:     'ఉత్పత్తులు',
  switcher_members:      'సభ్యులు',
  switcher_orders_today: 'ఈ రోజు ఆర్డర్లు',
  switcher_create_store: 'కొత్త స్టోర్ సృష్టించు',
  switcher_create_sub:   'HarvestConnect లో మరో స్టోర్‌ఫ్రంట్ సెటప్ చేయండి',
  switcher_created_msg:  'సృష్టించారు! వెరిఫైడ్ అవ్వడానికి KYC అప్‌లోడ్ చేయండి.',

  // Create store modal
  create_store_title:          'కొత్త స్టోర్ సృష్టించు',
  create_store_subtitle:       'మీ స్టోర్ అడ్మిన్ వెరిఫికేషన్ తర్వాత కనిపిస్తుంది',
  create_store_type:           'స్టోర్ రకం',
  create_store_name:           'స్టోర్ పేరు',
  create_store_name_ph:        'ఉదా. రవి ఆర్గానిక్ ఫార్మ్',
  create_store_phone:          'మొబైల్ నంబర్',
  create_store_phone_hint:     '10 అంకెల భారతీయ నంబర్ · స్టోర్ సంప్రదింపుగా ఉపయోగించబడుతుంది',
  create_store_phone_ph:       'ఉదా. 9876543210',
  create_store_location:       'లొకేషన్',
  create_store_location_hint:  'కొనుగోలుదారులకు చూపే పేరు',
  create_store_location_ph:    'ఉదా. నిజామాబాద్, తెలంగాణ',
  create_store_pincode:        'పిన్‌కోడ్',
  create_store_pincode_hint:   'డెలివరీ కోఆర్డినేట్‌లు సెట్ చేయడానికి ఉపయోగించబడుతుంది',
  create_store_pincode_ph:     '6 అంకెల పిన్‌కోడ్',
  create_store_zones:          'డెలివరీ జోన్లు',
  create_store_desc:           'వివరణ',
  create_store_desc_hint:      'ఐచ్ఛికం · మీ స్టోర్ ప్రొఫైల్‌లో చూపబడుతుంది',
  create_store_desc_ph:        'మీరు ఏమి అమ్ముతారో మరియు మీ స్టోర్‌ను ప్రత్యేకంగా చేసేది ఏమిటో చెప్పండి…',
  create_store_fssai:          'FSSAI లైసెన్స్ నంబర్',
  create_store_fssai_hint:     'ఐచ్ఛికం · ఆహార విక్రేతలకు అవసరం',
  create_store_fssai_ph:       '14 అంకెల FSSAI నంబర్',
  create_store_btn:            'స్టోర్ సృష్టించు',
  create_store_note:           'కొత్త స్టోర్లు అయాచిత స్థితిలో ప్రారంభమవుతాయి. వెరిఫైడ్ బ్యాడ్జ్ పొందడానికి KYC పత్రాలు అప్‌లోడ్ చేయండి.',
  create_store_err_name:       'స్టోర్ పేరు తప్పనిసరి',
  create_store_err_phone:      'సరైన 10 అంకెల భారతీయ మొబైల్ నంబర్ నమోదు చేయండి',
  create_store_err_location:   'లొకేషన్ తప్పనిసరి (ఉదా. నిజామాబాద్, తెలంగాణ)',
  create_store_err_pincode:    'సరైన 6 అంకెల పిన్‌కోడ్ నమోదు చేయండి',
  create_store_err_zones:      'కనీసం ఒక డెలివరీ జోన్ ఎంచుకోండి',

  // Invite member modal
  invite_title:             'టీమ్ మెంబర్ ఆహ్వానించు',
  invite_name:              'పూర్తి పేరు',
  invite_name_ph:           'ఉదా. రమేష్ కుమార్',
  invite_phone:             'మొబైల్ నంబర్',
  invite_phone_ph:          '+91 98765 43210',
  invite_role:              'పాత్ర',
  invite_role_manager:      'మేనేజర్',
  invite_role_manager_desc: 'ఉత్పత్తులు సవరించవచ్చు & విశ్లేషణలు చూడవచ్చు',
  invite_role_staff:        'సిబ్బంది',
  invite_role_staff_desc:   'ఆర్డర్లు మాత్రమే ప్రాసెస్ చేయవచ్చు',
  invite_hint:              'వారు HarvestConnect లో మీ స్టోర్‌లో చేరడానికి SMS ఆహ్వానం అందుకుంటారు.',
  invite_sending:           'పంపుతోంది...',
  invite_send:              'ఆహ్వానం పంపు',

  // Profile / Store screen extras
  profile_stat_products:     'ఉత్పత్తులు',
  profile_stat_orders:       'మొత్తం ఆర్డర్లు',
  profile_stat_rating:       'రేటింగ్',
  profile_stat_gmv:          'మొత్తం GMV',
  profile_identity:          'గుర్తింపు & సమ్మతి',
  profile_identity_sub:      'ఆధార్ · FSSAI · బ్యాంక్ ఖాతా',
  profile_payout_account:    'చెల్లింపు ఖాతా',
  profile_bank_not_setup:    'ఇంకా సెటప్ చేయలేదు',
  profile_change_bank:       'మార్చు',
  profile_add_bank:          'జోడించు',
  profile_delivery_coverage: 'డెలివరీ కవరేజ్',
  profile_no_zones:          'డెలివరీ జోన్‌లు కాన్ఫిగర్ చేయలేదు',
  profile_edit_coverage:     'సవరించు ›',
  profile_fssai_title:       'FSSAI లైసెన్స్',
  profile_fssai_not_provided:'అందించలేదు',
  profile_fssai_active:      'చురుకుగా',
  profile_fssai_pending:     'పెండింగ్',
  profile_switch:            'మార్చు ›',
  profile_viewing:           'చూస్తున్నారు',
  profile_store_live:        '● లైవ్',
  profile_store_offline:     '○ ఆఫ్‌లైన్',
  profile_member_active:     'చురుకుగా',
  profile_member_pending:    'పెండింగ్',
  profile_you:               '(మీరు)',
  profile_invited:           'ఆహ్వానించబడింది',
  profile_joined:            'చేరారు',
  profile_logout_btn:        '🚪  లాగ్‌అవుట్',
  profile_logout_title:      'లాగ్ అవుట్',
  profile_logout_msg:        'మీరు HarvestConnect Seller నుండి లాగ్ అవుట్ చేయాలనుకుంటున్నారా?',
  profile_logout_cancel:     'రద్దు చేయి',
  profile_logout_confirm:    'లాగ్ అవుట్',
  profile_tier_title:        'గోల్డ్ సెల్లర్ · HarvestConnect',
  profile_tier_sub:          'టాప్ 5% విక్రేతలు · ఫీచర్డ్ ప్లేస్‌మెంట్‌కు అర్హత · ప్రాధాన్య మద్దతు',
  profile_invite_count:      'స్టోర్ ఆహ్వానం',
  profile_invite_count_p:    'స్టోర్ ఆహ్వానాలు',
  profile_invite_sub:        'సమీక్షించడానికి మరియు అంగీకరించడానికి నొక్కండి',
  menu_store_settings_desc:  'స్టోర్ పేరు, ఫోటో, వివరణ, వర్గం',
  menu_my_products:          'నా ఉత్పత్తులు',
  menu_my_products_desc:     'మీ ఉత్పత్తి కాటలాగ్ నిర్వహించండి',
  menu_order_history:        'ఆర్డర్ చరిత్ర',
  menu_order_history_desc:   'అన్ని పూర్తయిన మరియు రద్దు చేయబడిన ఆర్డర్లు',
  menu_bank_payouts_desc:    'చెల్లింపు ఖాతా నిర్వహించండి · T+1 పరిష్కారం',
  menu_tx_history:           'లావాదేవీ చరిత్ర',
  menu_tx_history_desc:      'అన్ని క్రెడిట్‌లు, డెబిట్‌లు మరియు కమీషన్లు',
  menu_delivery_zones:       'డెలివరీ జోన్‌లు',
  menu_delivery_zones_desc:  'మండలం, జిల్లా, రాష్ట్ర కవరేజ్ ప్రాంతాలు',
  menu_kyc:                  'KYC & పత్రాలు',
  menu_kyc_desc:             'ఆధార్, FSSAI, బ్యాంక్ వెరిఫికేషన్',
  menu_promotions:           'ప్రమోషన్లు & ఆఫర్లు',
  menu_promotions_desc:      'తగ్గింపులు మరియు బండిల్ డీల్‌లు సృష్టించండి',
  menu_share_store:          'నా స్టోర్ షేర్ చేయి',
  menu_share_store_desc:     'మీ స్టోర్‌ఫ్రంట్ లింక్ షేర్ చేయండి',
  menu_reviews:              'సమీక్షలు & రేటింగ్‌లు',
  menu_reviews_desc:         '4.8 సగటు · 342 సమీక్షలు',
  menu_help:                 'సహాయం & మద్దతు',
  menu_help_desc:            'FAQs, సంప్రదింపు, విక్రేత గైడ్‌లు',
  menu_app_settings:         'యాప్ సెట్టింగ్‌లు',
  menu_app_settings_desc:    'నోటిఫికేషన్లు, భాష, గోప్యత',
  menu_social_handles:       'సోషల్ మీడియా',
  menu_social_handles_desc:  'Instagram, Facebook, WhatsApp & మరిన్ని',

  // Order detail modal
  order_detail_placed:              'ఉంచబడింది',
  order_detail_timeline_placed:     'ఆర్డర్ చేయబడింది',
  order_detail_timeline_accepted:   'స్వీకరించబడింది',
  order_detail_timeline_dispatched: 'పంపబడింది',
  order_detail_timeline_delivered:  'డెలివరీ అయింది',
  order_detail_cancelled:           'రద్దు చేయబడింది',
  order_detail_refund_init:         'రిఫండ్ ప్రారంభించబడింది',
  order_detail_refunded:            'రిఫండ్ చేయబడింది',
  order_detail_buyer:               'కొనుగోలుదారు',
  order_detail_call:                'కాల్ చేయి',
  order_detail_items:               'వస్తువులు',
  order_detail_payment:             'చెల్లింపు వివరాలు',
  order_detail_subtotal:            'ఉపమొత్తం',
  order_detail_delivery_fee:        'డెలివరీ ఫీజు',
  order_detail_discount:            'తగ్గింపు',
  order_detail_total:               'మొత్తం',
  order_detail_pay_method:          'చెల్లింపు',
  order_detail_tracking:            'ట్రాకింగ్',
  order_detail_est_delivery:        'అంచనా డెలివరీ:',
  order_detail_decline:             'తిరస్కరించు',
  order_detail_processing:          'ప్రాసెస్ అవుతోంది...',

  // Order filter modal
  filter_orders_title:  'ఆర్డర్లు ఫిల్టర్ చేయి',
  filter_payment_label: 'చెల్లింపు పద్ధతి',
  filter_all:           'అన్నీ',
  filter_upi:           'UPI',
  filter_cod:           'COD',
  filter_card:          'కార్డ్',
  filter_wallet:        'వాలెట్',
  filter_clear:         'ఫిల్టర్లు క్లియర్ చేయి',
  filter_done:          'పూర్తయింది',
  filter_hint_prefix:   'ఫిల్టర్ చేయబడింది:',
  filter_clear_x:       'క్లియర్ ✕',

  // Decline reason modal
  decline_title:        'ఆర్డర్ తిరస్కరించు',
  decline_reason_label: 'తిరస్కరణకు కారణం *',
  decline_placeholder:  'ఉదా: వస్తువు స్టాక్ అయిపోయింది, ఈ స్థానానికి డెలివరీ చేయలేము...',
  decline_hint:         'కొనుగోలుదారుకు ఈ కారణంతో నోటిఫికేషన్ వస్తుంది.',
  decline_cancel:       'రద్దు చేయి',
  decline_confirm:      'ఆర్డర్ తిరస్కరించు',
  decline_loading:      'తిరస్కరిస్తోంది...',

  // Product detail modal
  product_detail_title:      'ఉత్పత్తి వివరాలు',
  product_detail_no_images:  'చిత్రాలు జోడించలేదు',
  product_detail_desc:       'వివరణ',
  product_detail_rating:     'రేటింగ్',
  product_detail_reviews:    'సమీక్షలు',
  product_detail_listed:     'లిస్ట్ చేయబడింది',
  product_detail_to_draft:   '○ డ్రాఫ్ట్‌కు తరలించు',
  product_detail_make_live:  '● లైవ్ చేయి',
  product_detail_edit:       '✏️ ఉత్పత్తి సవరించు',
  product_detail_live:       '● లైవ్',
  product_detail_draft:      '○ డ్రాఫ్ట్',
  product_detail_archived_lbl:'✕ ఆర్కైవ్',
  product_detail_handmade:   '🪡 హస్తకళ',
  product_detail_verified:   '✓ నిర్ధారించబడింది',
  product_detail_out_stock:  'స్టాక్ అయిపోయింది',
  product_detail_low_stock:  'తక్కువ స్టాక్',
  product_detail_in_stock:   'స్టాక్‌లో ఉంది',
  product_detail_units:      'యూనిట్లు',
  product_detail_left:       'మిగిలింది',
  product_detail_alert:      'హెచ్చరిక',

  // Help & Support modal
  help_title:         'సహాయం & మద్దతు',
  help_hint:          'దిగువ సాధారణ ప్రశ్నలు చూడండి లేదా మా విక్రేత మద్దతు బృందాన్ని నేరుగా సంప్రదించండి.',
  help_faqs:          'తరచుగా అడిగే ప్రశ్నలు',
  help_contact:       'ఇంకా సహాయం కావాలా?',
  help_call:          'సపోర్ట్ కాల్',
  help_call_hours:    'సోమ–శని, ఉ.9 – సా.6',
  help_whatsapp:      'వాట్సాప్',
  help_whatsapp_sub:  'చాట్ ద్వారా త్వరిత సమాధానాలు',
  help_email:         'మాకు ఇమెయిల్ చేయండి',
  help_email_sub:     'seller-support@harvestconnect.in',
  help_guide:         '📖  విక్రేత గైడ్ & ఉత్తమ పద్ధతులు',
  help_guide_sub:     'ధర నిర్ణయం, ఛాయాచిత్రం మరియు అమ్మకాలు పెంచుకోవడంపై చిట్కాలు',
  help_faq_q1: 'కొత్త ఆర్డర్‌ను ఎలా స్వీకరించాలి?',
  help_faq_a1: 'ఆర్డర్లు ట్యాబ్‌కు వెళ్ళండి. కొత్త ఆర్డర్లు "కొత్త" విభాగంలో కనిపిస్తాయి. ఆర్డర్ కార్డ్ నొక్కి "స్వీకరించు" నొక్కండి — ఆర్డర్ స్వీకరించబడి కొనుగోలుదారుకు నోటిఫికేషన్ వస్తుంది.',
  help_faq_q2: 'నాకు ఎప్పుడు మరియు ఎలా చెల్లింపు అందుతుంది?',
  help_faq_a2: 'డెలివరీ నిర్ధారణ తర్వాత తదుపరి వ్యాపార దినాన (T+1) చెల్లింపులు జమ అవుతాయి. మీ నమోదిత బ్యాంక్ ఖాతాకు నేరుగా బదిలీ అవుతాయి. విశ్లేషణ స్క్రీన్‌లో చెల్లింపులు ట్రాక్ చేయవచ్చు.',
  help_faq_q3: 'ఉత్పత్తిని ఎలా జోడించాలి లేదా సవరించాలి?',
  help_faq_a3: 'ఉత్పత్తులు ట్యాబ్‌కు వెళ్ళండి. కొత్త లిస్టింగ్ సృష్టించడానికి "＋ ఉత్పత్తి జోడించు" నొక్కండి, లేదా ఏదైనా ఉత్పత్తి నొక్కి సవరించండి. ధర, స్టాక్, చిత్రాలు మరియు వివరణ ఏ సమయంలోనైనా నవీకరించవచ్చు.',
  help_faq_q4: 'HarvestConnect ఎంత కమీషన్ వసూలు చేస్తుంది?',
  help_faq_a4: 'HarvestConnect విజయవంతంగా డెలివరీ చేయబడిన ప్రతి ఆర్డర్‌పై 7% కమీషన్ వసూలు చేస్తుంది. మీరు ఆర్డర్ విలువలో 93% సంపాదిస్తారు. చెల్లింపు బదిలీ ముందు కమీషన్ తీసివేయబడుతుంది.',
  help_faq_q5: 'నా స్టోర్‌ను వెరిఫై చేయించుకోవడం ఎలా?',
  help_faq_a5: 'ప్రొఫైల్ → KYC & పత్రాల ద్వారా మీ FSSAI లైసెన్స్ నంబర్ మరియు సహాయక పత్రాలు అప్‌లోడ్ చేయండి. మా సమ్మతి బృందం వ్యాపార దినాలలో 48 గంటల్లోపు సమర్పణలను సమీక్షిస్తుంది.',
  help_faq_q6: 'ఆర్డర్‌ను రద్దు చేయడం లేదా తిరస్కరించడం ఎలా?',
  help_faq_a6: 'కొత్త (స్వీకరించని) ఆర్డర్లకు: ఆర్డర్ నొక్కి "తిరస్కరించు" నొక్కి కారణం నమోదు చేయండి. నెరవేర్చలేని స్వీకరించిన ఆర్డర్లకు నేరుగా సపోర్ట్‌ను సంప్రదించండి.',
  help_faq_q7: 'డెలివరీ జోన్‌లను ఎలా నవీకరించాలి?',
  help_faq_a7: 'ప్రొఫైల్ → డెలివరీ జోన్‌లకు వెళ్ళండి (లేదా డెలివరీ కవరేజ్ కార్డ్‌లో "సవరించు ›" నొక్కండి). మీరు సేవ అందించగల జోన్‌లు ఎంచుకుని సేవ్ చేయండి. కొత్త కొనుగోలుదారు శోధనలకు వెంటనే మార్పులు అమలవుతాయి.',
  help_faq_q8: 'నాకు అనేక స్టోర్లు ఉండవచ్చా?',
  help_faq_a8: 'అవును. స్టోర్ స్విచ్చర్ తెరవడానికి ఏ స్క్రీన్ పై భాగంలోని స్టోర్ చిహ్నం నొక్కండి. అదనపు స్టోర్‌ఫ్రంట్ సెట్ అప్ చేయడానికి "కొత్త స్టోర్ సృష్టించు" నొక్కండి.',

  // Transaction history modal
  tx_title:             'లావాదేవీ చరిత్ర',
  tx_total_credited:    'మొత్తం క్రెడిట్',
  tx_total_debited:     'మొత్తం డెబిట్',
  tx_net_balance:       'నికర బాలెన్స్',
  tx_filter_all:        'అన్నీ',
  tx_filter_credits:    'క్రెడిట్లు',
  tx_filter_debits:     'డెబిట్లు',
  tx_filter_commission: 'కమీషన్',
  tx_empty_title:       'ఇంకా లావాదేవీలు లేవు',
  tx_empty_all:         'పూర్తయిన ఆర్డర్లు ఇక్కడ క్రెడిట్లు మరియు కమీషన్లుగా కనిపిస్తాయి.',
  tx_empty_filter:      'లావాదేవీలు కనుగొనబడలేదు.',
  tx_type_credit:       'క్రెడిట్',
  tx_type_debit:        'డెబిట్',
  tx_type_commission:   'కమీషన్',

  // Delivery zones modal
  zones_title:           'డెలివరీ జోన్లు',
  zones_hint:            'మీరు డెలివరీ చేయగల అన్ని ప్రాంతాలు ఎంచుకోండి. మీ ఎంచుకున్న జోన్ల వెలుపలి కొనుగోలుదారులకు మీ లిస్టింగ్‌లు కనిపించవు.',
  zones_desc_mandal:     'మీ మండలంలోని సమీప గ్రామాలు మరియు పట్టణాలు',
  zones_desc_district:   'మీ జిల్లాలోని అన్ని ప్రాంతాలు',
  zones_desc_state:      'తెలంగాణ & ఆంధ్రప్రదేశ్ అంతటా',
  zones_desc_national:   'కూరియర్ భాగస్వామి ద్వారా పాన్-ఇండియా డెలివరీ',
  zones_saving:          'సేవ్ అవుతోంది…',
  zones_save_pre:        'సేవ్ ·',
  zones_zone:            'జోన్',
  zones_zones:           'జోన్లు',

  // Edit store modal
  edit_store_title:        'స్టోర్ సవరించు',
  edit_store_name:         'స్టోర్ పేరు',
  edit_store_name_ph:      'ఉదా: దేశీ డైరీ ఆర్మూర్',
  edit_store_desc:         'వివరణ',
  edit_store_desc_ph:      'కొనుగోలుదారులకు మీ స్టోర్, మీ ఉత్పాదన, మీ కథ గురించి చెప్పండి…',
  edit_store_location:     'స్థానం',
  edit_store_location_ph:  'ఉదా: నిజామాబాద్, తెలంగాణ',
  edit_store_address:      'స్టోర్ చిరునామా',
  edit_store_address_ph:   'వీధి, ప్రాంతం, ల్యాండ్‌మార్క్ — మీ స్టోర్ ప్రొఫైల్‌లో చూపబడుతుంది',
  edit_store_social:       'సోషల్ మీడియా హ్యాండిల్స్',
  edit_store_instagram:    'ఇన్‌స్టాగ్రామ్',
  edit_store_instagram_ph: 'yourhandle',
  edit_store_facebook:     'ఫేస్‌బుక్',
  edit_store_facebook_ph:  'facebook.com/yourpage',
  edit_store_whatsapp:     'వాట్సాప్ బిజినెస్',
  edit_store_whatsapp_ph:  '+91 98765 43210',
  edit_store_website:      'వెబ్‌సైట్',
  edit_store_website_ph:   'https://yourwebsite.com',
  edit_store_youtube:      'యూట్యూబ్ ఛానెల్',
  edit_store_youtube_ph:   'youtube.com/@yourchannel',
  edit_store_type:         'స్టోర్ రకం',
  edit_store_status:       'స్టోర్ స్థితి',
  edit_store_live_desc:    'కనిపించే · ఆర్డర్లు స్వీకరిస్తోంది',
  edit_store_offline_desc: 'కొనుగోలుదారులకు కనిపించదు',
  edit_store_saving:       'సేవ్ అవుతోంది…',
  edit_store_save:         'మార్పులు సేవ్ చేయి',

  // Bank account modal
  bank_title_add:        'బ్యాంక్ ఖాతా జోడించు',
  bank_title_update:     'బ్యాంక్ ఖాతా నవీకరించు',
  bank_subtitle:         'చెల్లింపులు T+1 లో ఈ ఖాతాకు జమ అవుతాయి',
  bank_holder_name:      'ఖాతాదారు పేరు',
  bank_holder_name_ph:   'బ్యాంక్ రికార్డుల ప్రకారం',
  bank_account_no:       'ఖాతా నంబర్',
  bank_account_no_ph:    'పూర్తి ఖాతా నంబర్ నమోదు చేయండి',
  bank_account_reenter:  'మళ్ళీ నమోదు చేయండి',
  bank_ifsc:             'IFSC కోడ్',
  bank_ifsc_ph:          'ఉదా: HDFC0001234',
  bank_name:             'బ్యాంక్ పేరు',
  bank_name_ph:          'ఉదా: HDFC బ్యాంక్',
  bank_upi:              'UPI ID',
  bank_upi_hint:         'ఐచ్ఛికం — వేగవంతమైన జమల కోసం',
  bank_upi_ph:           'ఉదా: name@hdfcbank',
  bank_save_btn:         'ఖాతా సేవ్ చేయి',
  bank_update_btn:       'ఖాతా నవీకరించు',
  bank_err_holder:       'ఖాతాదారు పేరు అవసరం',
  bank_err_account:      'ఖాతా నంబర్ 9–18 అంకెలు అయి ఉండాలి',
  bank_err_ifsc:         'చెల్లని IFSC కోడ్ (ఉదా: HDFC0001234)',
  bank_err_bank_name:    'బ్యాంక్ పేరు అవసరం',
  bank_err_save:         'సేవ్ చేయడం విఫలమైంది. దయచేసి మళ్ళీ ప్రయత్నించండి.',

  // KYC & documents modal
  kyc_title:             'KYC & పత్రాలు',
  kyc_verified_title:    'KYC నిర్ధారించబడింది',
  kyc_pending_title:     'నిర్ధారణ పెండింగ్‌లో ఉంది',
  kyc_verified_sub:      'మీ ఖాతా నిర్ధారించబడింది మరియు చెల్లింపులకు పూర్తిగా అర్హమైనది.',
  kyc_pending_sub:       'మీ FSSAI నంబర్ మరియు సహాయక పత్రాలు సమర్పించండి. అడ్మిన్ 48 గంటల్లోపు సమీక్షిస్తారు.',
  kyc_fssai_label:       'FSSAI లైసెన్స్ నంబర్',
  kyc_fssai_hint:        'మీ FSSAI ఆహార లైసెన్స్ సర్టిఫికేట్ నుండి 14 అంకెల నంబర్',
  kyc_docs_label:        'సహాయక పత్రాలు',
  kyc_no_docs:           'ఇంకా పత్రాలు అప్‌లోడ్ చేయలేదు',
  kyc_doc_url_ph:        'పత్ర URL అతికించండి (Google Drive, Dropbox…)',
  kyc_doc_add:           'జోడించు',
  kyc_upload_hint:       'కెమెరా & గ్యాలరీ అప్‌లోడ్ త్వరలో వస్తుంది. ఇప్పటికి, మీ పత్రాన్ని Google Drive లేదా Dropbox లో హోస్ట్ చేసి పైన షేరబుల్ లింక్ అతికించండి.',
  kyc_accepted_title:    'అంగీకరించబడిన పత్రాలు',
  kyc_accepted_1:        'ఆధార్ కార్డ్ (రెండు వైపులు)',
  kyc_accepted_2:        'PAN కార్డ్',
  kyc_accepted_3:        'FSSAI లైసెన్స్ సర్టిఫికేట్',
  kyc_accepted_4:        'బ్యాంక్ ఖాతా స్టేట్‌మెంట్ / పాస్‌బుక్',
  kyc_accepted_5:        'GST సర్టిఫికేట్ (వర్తించే పక్షంలో)',
  kyc_saving:            'సేవ్ అవుతోంది…',
  kyc_save:              'సేవ్ చేయి',

  // Promotions modal
  promo_title:           'ప్రమోషన్లు & ఆఫర్లు',
  promo_new_form_title:  'కొత్త ప్రమోషన్',
  promo_type_label:      'ప్రమోషన్ రకం',
  promo_type_percent:    '% తగ్గింపు',
  promo_type_flat:       'ఫ్లాట్ ₹ తగ్గింపు',
  promo_type_free_del:   'ఉచిత డెలివరీ',
  promo_disc_pct:        'తగ్గింపు శాతం *',
  promo_disc_flat:       'తగ్గింపు మొత్తం *',
  promo_min_order:       'కనీస ఆర్డర్ మొత్తం (ఐచ్ఛికం)',
  promo_valid_for:       'చెల్లుబాటు వ్యవధి',
  promo_days:            'రోజులు',
  promo_1_month:         '1 నెల',
  promo_create:          'సృష్టించు',
  promo_new_btn:         'కొత్త ప్రమోషన్ సృష్టించు',
  promo_new_sub:         'తగ్గింపులు, ఉచిత డెలివరీ మరియు మరిన్ని',
  promo_empty_title:     'చురుకైన ప్రమోషన్లు లేవు',
  promo_empty_sub:       'మరింత మంది కొనుగోలుదారులను ఆకర్షించడానికి మరియు మీ అమ్మకాలు పెంచుకోవడానికి తగ్గింపు లేదా ఆఫర్ సృష్టించండి.',
  promo_min_order_label: 'కనీస ఆర్డర్ ₹',
  promo_valid_pre:       'చెల్లుబాటు',
  promo_active:          'చురుకుగా ఉంది',
  promo_paused:          'నిలిపివేయబడింది',
  promo_pause:           'నిలిపివేయి',
  promo_resume:          'తిరిగి ప్రారంభించు',
  promo_delete:          'తొలగించు',
  promo_off:             'తగ్గింపు',
  promo_created_toast:   'ప్రమోషన్ సృష్టించబడింది!',
  promo_removed_toast:   'ప్రమోషన్ తొలగించబడింది.',
  promo_sync_note:       'ప్రమోషన్లు ప్రస్తుతం సెషన్ మాత్రమే. ప్రమోషన్ సేవ ప్రారంభమైన తర్వాత శాశ్వత నిర్వహణ అందుబాటులోకి వస్తుంది.',

  // Kirana business model toggle
  create_store_business_model:    'వ్యాపార నమూనా',
  create_store_retail:            'రిటైల్',
  create_store_retail_sub:        'వినియోగదారులకు అమ్మకం',
  create_store_wholesale:         'హోల్‌సేల్',
  create_store_wholesale_sub:     'దుకాణాలు / రీసెల్లర్‌లకు',

  // Custom delivery area (create-store)
  create_store_custom_area_on:    '✕ కస్టమ్ ప్రాంతం',
  create_store_custom_area_off:   '+ కస్టమ్ ప్రాంతం',
  create_store_custom_area_title: 'కస్టమ్ డెలివరీ ప్రాంతం ఎంపిక చేయబడింది',
  create_store_custom_area_desc:  'స్టోర్ సృష్టి తర్వాత స్టోర్ సెట్టింగ్‌ల నుండి నిర్దిష్ట మండలాలు, జిల్లాలు, పిన్‌కోడ్‌లు మరియు రాష్ట్రాలు నిర్వచించవచ్చు.',

  // Duplicate store type warning
  create_store_dup_title_prefix:  'మీకు ఇప్పటికే ఒక',
  create_store_dup_title_suffix:  'స్టోర్ ఉంది',
  create_store_dup_desc:          'మరో స్టోర్ సృష్టించడం అనుమతించబడుతుంది, కానీ మీ ప్రస్తుత స్టోర్‌ని వాడటం పరిగణించండి. మీకు ఖచ్చితంగా ఉందా?',
  create_store_dup_confirm:       'అయినా సృష్టించు',

  // Product form — new fields
  product_form_moq_label:         'కనీస ఆర్డర్ పరిమాణం (MOQ)',
  product_form_custom_area:       'కస్టమ్ ప్రాంతం',
  product_form_custom_area_title: 'కస్టమ్ డెలివరీ ప్రాంతం',
  product_form_custom_area_desc:  'మీ స్టోర్ యొక్క కస్టమ్ డెలివరీ ప్రాంతానికి పంపుతుంది',
};

const HI: typeof EN = {
  // Tabs
  tab_dashboard:  'डैशबोर्ड',
  tab_products:   'उत्पाद',
  tab_orders:     'ऑर्डर',
  tab_analytics:  'विश्लेषण',
  tab_store:      'स्टोर',

  // App Settings modal
  settings_title: 'ऐप सेटिंग्स',

  settings_notifications:   'सूचनाएं',
  notif_new_orders:         'नए ऑर्डर',
  notif_new_orders_desc:    'जब कोई खरीदार नया ऑर्डर दे तो अलर्ट',
  notif_order_updates:      'ऑर्डर स्थिति अपडेट',
  notif_order_updates_desc: 'ऑर्डर भेजे या डिलीवर होने पर अपडेट',
  notif_payment:            'भुगतान प्राप्त हुआ',
  notif_payment_desc:       'जब आपके बैंक में भुगतान ट्रांसफर हो तो अलर्ट',
  notif_performance:        'साप्ताहिक रिपोर्ट',
  notif_performance_desc:   'हर सोमवार आपके स्टोर के प्रदर्शन का सारांश',
  notif_promos:             'हार्वेस्टकनेक्ट अपडेट',
  notif_promos_desc:        'नई सुविधाएं, विक्रेता कार्यक्रम और सुझाव',

  settings_display:         'प्रदर्शन',
  display_language:         'भाषा',
  display_dark_mode:        'डार्क मोड',
  display_dark_mode_desc:   'अपनी पसंदीदा थीम चुनें',
  theme_light:              'लाइट',
  theme_dark:               'डार्क',
  theme_system:             'सिस्टम',
  coming_soon:              'जल्द आ रहा है',

  settings_privacy:         'गोपनीयता और कानूनी',
  privacy_policy:           'गोपनीयता नीति',
  terms_of_service:         'सेवा की शर्तें',
  data_permissions:         'डेटा और अनुमतियां',

  settings_about:           'के बारे में',
  about_version:            'ऐप संस्करण',
  about_platform:           'प्लेटफ़ॉर्म',

  // Dashboard screen
  dash_todays_performance:  'आज का प्रदर्शन',
  dash_quick_actions:       'त्वरित क्रियाएं',
  dash_add_product:         'उत्पाद जोड़ें',
  dash_view_orders:         'ऑर्डर देखें',
  dash_request_payout:      'भुगतान अनुरोध करें',
  dash_analytics:           'विश्लेषण',
  dash_incoming_orders:     'आने वाले ऑर्डर',
  dash_requires_attention:  'आपका ध्यान चाहिए',
  dash_view_all:            'सभी देखें ›',
  dash_no_pending_orders:   'कोई लंबित ऑर्डर नहीं',
  dash_loading_orders:      'लोड हो रहा है...',
  dash_store_health:        'स्टोर स्वास्थ्य',
  dash_fulfilment_rate:     'पूर्ति दर',
  dash_avg_response:        'औसत प्रतिक्रिया',
  dash_store_rating:        'स्टोर रेटिंग',
  dash_cancel_rate:         'रद्द दर',
  dash_accept_order:        'ऑर्डर स्वीकार करें',
  dash_decline:             'अस्वीकार करें',
  dash_mark_dispatched:     'भेजा गया चिह्नित करें 🚚',
  dash_processing:          'प्रोसेस हो रहा है...',
  dash_todays_revenue:      'आज का राजस्व',
  dash_new_orders:          'नए ऑर्डर',
  dash_pending:             'लंबित',
  dash_store_views:         'स्टोर दर्शन',
  dash_tip_title:           'सुझाव: फसल की फ़ोटो जोड़ें',
  dash_tip_sub:             'खेत की फ़ोटो वाली लिस्टिंग को 3× अधिक क्लिक मिलते हैं। अपने शीर्ष 3 उत्पादों में फ़ोटो जोड़ें।',
  dash_good_morning:        'सुप्रभात',
  dash_good_afternoon:      'नमस्कार',
  dash_good_evening:        'शुभ संध्या',
  dash_available_payout:    'भुगतान के लिए उपलब्ध',
  dash_t1_settlement:       'T+1 निपटान · अनुरोध करने के लिए टैप करें',

  // Payout modal
  payout_title:             'भुगतान',
  payout_available_label:   'भुगतान के लिए उपलब्ध',
  payout_delivered_after:   '7% कमीशन के बाद',
  payout_delivered_orders:  'डिलीवर ऑर्डर',
  payout_delivered_orders_p:'डिलीवर ऑर्डर',
  payout_breakdown:         'विवरण',
  payout_order_revenue:     'ऑर्डर राजस्व',
  payout_commission:        'प्लेटफ़ॉर्म कमीशन (7%)',
  payout_you_earn:          'आप कमाते हैं',
  payout_transfer_to:       'ट्रांसफर करें',
  payout_verified:          'सत्यापित',
  payout_no_bank:           'कोई बैंक खाता लिंक नहीं है। जोड़ने के लिए प्रोफ़ाइल → बैंक और भुगतान पर जाएं।',
  payout_t1_info:           'भुगतान T+1 में प्रोसेस होते हैं — अनुरोध के बाद अगले व्यावसायिक दिन धनराशि आती है।',
  payout_no_orders:         'अभी तक कोई डिलीवर ऑर्डर नहीं। खरीदारों की पुष्टि के बाद राशि उपलब्ध होगी।',
  payout_close:             'बंद करें',
  payout_request_btn:       'भुगतान अनुरोध करें →',
  payout_no_balance:        'बैलेंस नहीं',
  payout_confirm_title:     'भुगतान अनुरोध की पुष्टि करें',
  payout_bank_required_title: 'बैंक खाता आवश्यक है',
  payout_bank_required_msg: 'अनुरोध करने से पहले प्रोफ़ाइल → बैंक और भुगतान में बैंक खाता जोड़ें।',
  payout_success_toast:     'भुगतान अनुरोध किया गया! अगले व्यावसायिक दिन धनराशि आएगी।',
  payout_cancel:            'रद्द करें',
  payout_request_now:       'अभी अनुरोध करें',

  // Orders screen
  orders_new:               'नया',
  orders_accepted:          'स्वीकृत',
  orders_dispatched:        'भेजा गया',
  orders_delivered:         'डिलीवर हुआ',
  orders_cancelled:         'रद्द हुआ',
  orders_no_orders:         'कोई ऑर्डर नहीं',
  orders_loading:           'लोड हो रहा है...',
  orders_accept_order:      'ऑर्डर स्वीकार करें ✓',
  orders_mark_dispatched:   'भेजा गया चिह्नित करें 🚚',
  orders_mark_delivered:    'डिलीवर हुआ चिह्नित करें ✓',
  orders_decline:           'अस्वीकार करें',
  orders_processing:        'प्रोसेस हो रहा है...',
  orders_filter:            'फ़िल्टर',
  orders_total:             'कुल',

  // Analytics screen
  analytics_title:          'विश्लेषण',
  analytics_store_perf:     'स्टोर प्रदर्शन',
  analytics_export:         'निर्यात',
  analytics_loading:        'लोड हो रहा है…',
  analytics_total_revenue:  'कुल राजस्व',
  analytics_orders:         'ऑर्डर',
  analytics_avg_order:      'औसत ऑर्डर',
  analytics_revenue_breakdown: 'राजस्व विभाजन',
  analytics_buyer_insights: 'खरीदार अंतर्दृष्टि',
  analytics_new_buyers:     'नए खरीदार',
  analytics_returning:      'वापस आने वाले',
  analytics_repeat_rate:    'दोहराव दर',
  analytics_top_products:   'शीर्ष उत्पाद',
  analytics_payout_history: 'भुगतान इतिहास',
  analytics_view_all:       'सभी देखें ›',
  analytics_no_payouts:     'अभी तक कोई भुगतान नहीं — पूर्ण ऑर्डर यहाँ दिखाई देंगे।',
  analytics_next_payout:    'अगला भुगतान: आज रात 11 बजे',
  analytics_orders_settled: 'ऑर्डर निपटाए गए',
  analytics_no_pending_payout: 'कोई लंबित भुगतान नहीं',
  analytics_period_today:   'आज',
  analytics_period_week:    'इस सप्ताह',
  analytics_period_month:   'इस महीने',
  analytics_period_all:     'सभी समय',

  // Products screen
  products_title:           'मेरे उत्पाद',
  products_search_placeholder: 'उत्पाद खोजें...',
  products_loading:         'लोड हो रहा है...',
  products_filter_all:      'सभी',
  products_filter_active:   'सक्रिय',
  products_filter_draft:    'ड्राफ्ट',
  products_filter_archived: 'संग्रहीत',
  products_filter_low_stock: 'कम स्टॉक',
  products_add:             'उत्पाद जोड़ें',
  products_in_stock:        'स्टॉक में है',
  products_out_of_stock:    'स्टॉक खत्म',
  products_low_stock:       'कम',
  products_status_active:   'सक्रिय',
  products_status_draft:    'ड्राफ्ट',
  products_status_archived: 'संग्रहीत',
  products_no_products_yet: 'अभी तक कोई उत्पाद नहीं',
  products_no_products_found: 'कोई उत्पाद नहीं मिला',
  products_add_new:         'नया उत्पाद जोड़ें',

  // Store / Profile screen
  store_settings:           'स्टोर सेटिंग्स',
  store_team_members:       'टीम सदस्य',
  store_my_stores:          'मेरे स्टोर',
  store_bank_payouts:       'बैंक और भुगतान',
  store_invite_member:      'सदस्य आमंत्रित करें',
  store_loading:            'लोड हो रहा है',

  // Orders screen extras
  orders_header_title:      'ऑर्डर प्रबंधन',
  orders_placed:            'दिया गया',
  orders_empty_sub:         'जब ग्राहक ऑर्डर देंगे तो यहां दिखाई देंगे',
  orders_completed_txt:     'ऑर्डर पूर्ण हुआ',
  orders_after_commission:  '7% कमीशन के बाद कमाए',
  orders_cancel_reason:     'कारण:',
  orders_filter_hint:       'फ़िल्टर किया गया:',
  orders_filter_clear:      'साफ़ करें ✕',

  // Products screen extras
  products_selected:         'चुने गए',
  products_listings:         'लिस्टिंग',
  products_sel_hint:         'टॉगल करने के लिए कार्ड पर टैप करें · चयन शुरू करने के लिए लंबे समय तक दबाएं',
  products_cancel_sel:       '✕ रद्द करें',
  products_cant_load:        'उत्पाद लोड नहीं हो सके',
  products_retry:            'पुनः प्रयास करें',
  products_empty_add_sub:    '"+ जोड़ें" टैप करके अपना पहला उत्पाद सूचीबद्ध करें',
  products_empty_filter_sub: 'कोई अन्य खोज या फ़िल्टर आज़माएं',
  products_add_cta_sub:      'अपनी फसल, हस्तशिल्प या स्थानीय उत्पाद सूचीबद्ध करें',
  products_bulk_activate:    '● सक्रिय करें',
  products_bulk_archive:     'संग्रहीत करें',
  products_bulk_delete:      '🗑️ हटाएं',
  products_bulk_select_all:  'सभी चुनें',
  products_bulk_clear:       '✕ साफ़ करें',
  products_edit:             '✏️ संपादित करें',
  products_reviews:          'समीक्षाएं',
  products_ships_to:         '🚚 डिलीवरी:',

  // Analytics screen extras
  analytics_no_delivered:         'इस अवधि में कोई डिलीवर ऑर्डर नहीं',
  analytics_no_buyers:            'इस अवधि में कोई खरीदार डेटा नहीं',
  analytics_no_sales:             'इस अवधि में कोई बिक्री डेटा नहीं',
  analytics_units_sold:           'यूनिट बेची गईं',
  analytics_payout_transfer:      'आपके पंजीकृत बैंक खाते में ट्रांसफर किया जाएगा',
  analytics_payout_restricted:    'भुगतान डेटा प्रतिबंधित है',
  analytics_payout_restricted_sub:'केवल स्टोर मालिक ही भुगतान इतिहास और वित्तीय विवरण देख सकते हैं।',

  // Product form modal
  product_form_add_title:           'नया उत्पाद जोड़ें',
  product_form_edit_title:          'उत्पाद संपादित करें',
  product_form_listing_under:       'के तहत लिस्टिंग',
  product_form_name:                'उत्पाद का नाम',
  product_form_name_ph:             'जैसे. जैविक हल्दी पाउडर',
  product_form_desc:                'विवरण',
  product_form_desc_ph:             'खरीदारों को बताएं इसे खास क्या बनाता है — स्रोत, प्रक्रिया, गुणवत्ता...',
  product_form_category:            'श्रेणी',
  product_form_subcategory:         'उप-श्रेणी',
  product_form_price:               'मूल्य (₹)',
  product_form_orig_price:          'मूल / MRP (₹)',
  product_form_orig_price_hint:     'वैकल्पिक — बिक्री मूल्य से अधिक होने पर कटा हुआ मूल्य दिखेगा',
  product_form_stock:               'स्टॉक मात्रा',
  product_form_threshold:           'कम स्टॉक अलर्ट सीमा',
  product_form_threshold_hint:      'मात्रा इस संख्या से कम होने पर "कम स्टॉक" बैज मिलेगा',
  product_form_threshold_unit:      'इकाइयाँ',
  product_form_unit:                'इकाई',
  product_form_unit_ph:             'या कस्टम इकाई टाइप करें...',
  product_form_delivery:            'डिलीवरी दायरा',
  product_form_images:              'उत्पाद छवियाँ',
  product_form_pick_device:         '📷 डिवाइस से चुनें',
  product_form_paste_url:           'या छवि URL पेस्ट करें...',
  product_form_add_url:             'जोड़ें',
  product_form_status:              'लिस्टिंग स्थिति',
  product_form_status_active_desc:  'सक्रिय — खरीदारों को दिखाई देता है',
  product_form_status_draft_desc:   'ड्राफ्ट — खरीदारों से छिपा हुआ',
  product_form_draft:               'ड्राफ्ट',
  product_form_active:              'सक्रिय',
  product_form_handmade:            'हस्तनिर्मित / कारीगर',
  product_form_handmade_sub:        'हाथ से या स्थानीय शिल्प से बनाया गया',
  product_form_save:                '💾 परिवर्तन सहेजें',
  product_form_add_btn:             '＋ उत्पाद जोड़ें',
  product_form_err_name:            'उत्पाद का नाम आवश्यक है।',
  product_form_err_price:           'कृपया ₹ में वैध मूल्य दर्ज करें।',
  product_form_err_stock:           'वैध स्टॉक मात्रा दर्ज करें (0 या अधिक)।',
  product_form_img_limit:           'अधिकतम 5 छवियाँ जोड़ी जा सकती हैं।',

  // Store switcher
  switcher_title:        'स्टोर बदलें',
  switcher_managing:     'आप',
  switcher_stores:       'स्टोर प्रबंधित कर रहे हैं',
  switcher_products:     'उत्पाद',
  switcher_members:      'सदस्य',
  switcher_orders_today: 'आज के ऑर्डर',
  switcher_create_store: 'नया स्टोर बनाएं',
  switcher_create_sub:   'HarvestConnect पर एक और स्टोरफ्रंट सेट करें',
  switcher_created_msg:  'बनाया गया! सत्यापित होने के लिए KYC अपलोड करें।',

  // Create store modal
  create_store_title:          'नया स्टोर बनाएं',
  create_store_subtitle:       'आपका स्टोर एडमिन वेरिफिकेशन के बाद दिखाई देगा',
  create_store_type:           'स्टोर प्रकार',
  create_store_name:           'स्टोर का नाम',
  create_store_name_ph:        'जैसे. रवि ऑर्गेनिक फार्म',
  create_store_phone:          'मोबाइल नंबर',
  create_store_phone_hint:     '10 अंकों का भारतीय नंबर · स्टोर संपर्क के रूप में उपयोग होगा',
  create_store_phone_ph:       'जैसे. 9876543210',
  create_store_location:       'स्थान',
  create_store_location_hint:  'खरीदारों को दिखाया जाने वाला नाम',
  create_store_location_ph:    'जैसे. निज़ामाबाद, तेलंगाना',
  create_store_pincode:        'पिनकोड',
  create_store_pincode_hint:   'डिलीवरी निर्देशांक सेट करने के लिए उपयोग होगा',
  create_store_pincode_ph:     '6 अंकों का पिनकोड',
  create_store_zones:          'डिलीवरी क्षेत्र',
  create_store_desc:           'विवरण',
  create_store_desc_hint:      'वैकल्पिक · आपके स्टोर प्रोफ़ाइल पर दिखाया जाएगा',
  create_store_desc_ph:        'खरीदारों को बताएं आप क्या बेचते हैं और आपका स्टोर क्या खास है…',
  create_store_fssai:          'FSSAI लाइसेंस नंबर',
  create_store_fssai_hint:     'वैकल्पिक · खाद्य विक्रेताओं के लिए आवश्यक',
  create_store_fssai_ph:       '14 अंकों का FSSAI नंबर',
  create_store_btn:            'स्टोर बनाएं',
  create_store_note:           'नए स्टोर असत्यापित के रूप में शुरू होते हैं। वेरिफाइड बैज पाने के लिए KYC दस्तावेज़ अपलोड करें।',
  create_store_err_name:       'स्टोर का नाम आवश्यक है',
  create_store_err_phone:      'वैध 10 अंकों का भारतीय मोबाइल नंबर दर्ज करें',
  create_store_err_location:   'स्थान आवश्यक है (जैसे. निज़ामाबाद, तेलंगाना)',
  create_store_err_pincode:    'वैध 6 अंकों का पिनकोड दर्ज करें',
  create_store_err_zones:      'कम से कम एक डिलीवरी क्षेत्र चुनें',

  // Invite member modal
  invite_title:             'टीम सदस्य आमंत्रित करें',
  invite_name:              'पूरा नाम',
  invite_name_ph:           'जैसे. रमेश कुमार',
  invite_phone:             'मोबाइल नंबर',
  invite_phone_ph:          '+91 98765 43210',
  invite_role:              'भूमिका',
  invite_role_manager:      'मैनेजर',
  invite_role_manager_desc: 'उत्पाद संपादित कर सकते हैं और विश्लेषण देख सकते हैं',
  invite_role_staff:        'स्टाफ',
  invite_role_staff_desc:   'केवल ऑर्डर प्रोसेस कर सकते हैं',
  invite_hint:              'उन्हें HarvestConnect पर आपके स्टोर से जुड़ने के लिए SMS आमंत्रण मिलेगा।',
  invite_sending:           'भेजा जा रहा है...',
  invite_send:              'आमंत्रण भेजें',

  // Profile / Store screen extras
  profile_stat_products:     'उत्पाद',
  profile_stat_orders:       'कुल ऑर्डर',
  profile_stat_rating:       'रेटिंग',
  profile_stat_gmv:          'कुल GMV',
  profile_identity:          'पहचान और अनुपालन',
  profile_identity_sub:      'आधार · FSSAI · बैंक खाता',
  profile_payout_account:    'भुगतान खाता',
  profile_bank_not_setup:    'अभी तक सेट अप नहीं किया',
  profile_change_bank:       'बदलें',
  profile_add_bank:          'जोड़ें',
  profile_delivery_coverage: 'डिलीवरी कवरेज',
  profile_no_zones:          'कोई डिलीवरी क्षेत्र कॉन्फ़िगर नहीं',
  profile_edit_coverage:     'संपादित करें ›',
  profile_fssai_title:       'FSSAI लाइसेंस',
  profile_fssai_not_provided:'प्रदान नहीं किया',
  profile_fssai_active:      'सक्रिय',
  profile_fssai_pending:     'लंबित',
  profile_switch:            'बदलें ›',
  profile_viewing:           'देख रहे हैं',
  profile_store_live:        '● लाइव',
  profile_store_offline:     '○ ऑफलाइन',
  profile_member_active:     'सक्रिय',
  profile_member_pending:    'लंबित',
  profile_you:               '(आप)',
  profile_invited:           'आमंत्रित',
  profile_joined:            'शामिल हुए',
  profile_logout_btn:        '🚪  लॉगआउट',
  profile_logout_title:      'लॉग आउट',
  profile_logout_msg:        'क्या आप HarvestConnect Seller से लॉग आउट करना चाहते हैं?',
  profile_logout_cancel:     'रद्द करें',
  profile_logout_confirm:    'लॉग आउट',
  profile_tier_title:        'गोल्ड सेलर · HarvestConnect',
  profile_tier_sub:          'शीर्ष 5% विक्रेता · फीचर्ड प्लेसमेंट के लिए पात्र · प्राथमिकता सहायता',
  profile_invite_count:      'स्टोर आमंत्रण',
  profile_invite_count_p:    'स्टोर आमंत्रण',
  profile_invite_sub:        'समीक्षा और स्वीकार करने के लिए टैप करें',
  menu_store_settings_desc:  'स्टोर का नाम, फ़ोटो, विवरण, श्रेणी',
  menu_my_products:          'मेरे उत्पाद',
  menu_my_products_desc:     'अपना उत्पाद कैटलॉग प्रबंधित करें',
  menu_order_history:        'ऑर्डर इतिहास',
  menu_order_history_desc:   'सभी पूर्ण और रद्द किए गए ऑर्डर',
  menu_bank_payouts_desc:    'भुगतान खाता प्रबंधित करें · T+1 निपटान',
  menu_tx_history:           'लेनदेन इतिहास',
  menu_tx_history_desc:      'सभी क्रेडिट, डेबिट और कमीशन',
  menu_delivery_zones:       'डिलीवरी क्षेत्र',
  menu_delivery_zones_desc:  'मंडल, जिला, राज्य कवरेज क्षेत्र',
  menu_kyc:                  'KYC और दस्तावेज़',
  menu_kyc_desc:             'आधार, FSSAI, बैंक सत्यापन',
  menu_promotions:           'प्रमोशन और ऑफर',
  menu_promotions_desc:      'छूट और बंडल डील बनाएं',
  menu_share_store:          'मेरा स्टोर शेयर करें',
  menu_share_store_desc:     'अपना स्टोर लिंक शेयर करें',
  menu_reviews:              'समीक्षाएं और रेटिंग',
  menu_reviews_desc:         '4.8 औसत · 342 समीक्षाएं',
  menu_help:                 'सहायता और समर्थन',
  menu_help_desc:            'FAQs, संपर्क, विक्रेता गाइड',
  menu_app_settings:         'ऐप सेटिंग्स',
  menu_app_settings_desc:    'सूचनाएं, भाषा, गोपनीयता',
  menu_social_handles:       'सोशल मीडिया',
  menu_social_handles_desc:  'Instagram, Facebook, WhatsApp और अधिक',

  // Order detail modal
  order_detail_placed:              'दिया गया',
  order_detail_timeline_placed:     'ऑर्डर दिया गया',
  order_detail_timeline_accepted:   'स्वीकृत',
  order_detail_timeline_dispatched: 'भेजा गया',
  order_detail_timeline_delivered:  'डिलीवर हुआ',
  order_detail_cancelled:           'रद्द हुआ',
  order_detail_refund_init:         'रिफंड शुरू हुआ',
  order_detail_refunded:            'रिफंड हुआ',
  order_detail_buyer:               'खरीदार',
  order_detail_call:                'कॉल करें',
  order_detail_items:               'वस्तुएं',
  order_detail_payment:             'भुगतान विवरण',
  order_detail_subtotal:            'उपकुल',
  order_detail_delivery_fee:        'डिलीवरी शुल्क',
  order_detail_discount:            'छूट',
  order_detail_total:               'कुल',
  order_detail_pay_method:          'भुगतान',
  order_detail_tracking:            'ट्रैकिंग',
  order_detail_est_delivery:        'अनुमानित डिलीवरी:',
  order_detail_decline:             'अस्वीकार करें',
  order_detail_processing:          'प्रोसेस हो रहा है...',

  // Order filter modal
  filter_orders_title:  'ऑर्डर फ़िल्टर करें',
  filter_payment_label: 'भुगतान पद्धति',
  filter_all:           'सभी',
  filter_upi:           'UPI',
  filter_cod:           'COD',
  filter_card:          'कार्ड',
  filter_wallet:        'वॉलेट',
  filter_clear:         'फ़िल्टर हटाएं',
  filter_done:          'हो गया',
  filter_hint_prefix:   'फ़िल्टर किया गया:',
  filter_clear_x:       'हटाएं ✕',

  // Decline reason modal
  decline_title:        'ऑर्डर अस्वीकार करें',
  decline_reason_label: 'अस्वीकार करने का कारण *',
  decline_placeholder:  'जैसे: आइटम स्टॉक में नहीं है, इस स्थान पर डिलीवरी नहीं हो सकती...',
  decline_hint:         'खरीदार को इस कारण के साथ सूचित किया जाएगा।',
  decline_cancel:       'रद्द करें',
  decline_confirm:      'ऑर्डर अस्वीकार करें',
  decline_loading:      'अस्वीकार हो रहा है...',

  // Product detail modal
  product_detail_title:      'उत्पाद विवरण',
  product_detail_no_images:  'कोई छवि नहीं जोड़ी गई',
  product_detail_desc:       'विवरण',
  product_detail_rating:     'रेटिंग',
  product_detail_reviews:    'समीक्षाएं',
  product_detail_listed:     'सूचीबद्ध',
  product_detail_to_draft:   '○ ड्राफ्ट में ले जाएं',
  product_detail_make_live:  '● लाइव करें',
  product_detail_edit:       '✏️ उत्पाद संपादित करें',
  product_detail_live:       '● लाइव',
  product_detail_draft:      '○ ड्राफ्ट',
  product_detail_archived_lbl:'✕ संग्रहीत',
  product_detail_handmade:   '🪡 हस्तनिर्मित',
  product_detail_verified:   '✓ सत्यापित',
  product_detail_out_stock:  'स्टॉक खत्म',
  product_detail_low_stock:  'कम स्टॉक',
  product_detail_in_stock:   'स्टॉक में',
  product_detail_units:      'यूनिट',
  product_detail_left:       'बचे हैं',
  product_detail_alert:      'अलर्ट',

  // Help & Support modal
  help_title:         'सहायता और समर्थन',
  help_hint:          'नीचे सामान्य प्रश्न देखें या हमारी विक्रेता सहायता टीम से सीधे संपर्क करें।',
  help_faqs:          'अक्सर पूछे जाने वाले प्रश्न',
  help_contact:       'अभी भी मदद चाहिए?',
  help_call:          'सपोर्ट कॉल',
  help_call_hours:    'सोम–शनि, सुबह 9 – शाम 6',
  help_whatsapp:      'व्हाट्सएप',
  help_whatsapp_sub:  'चैट के ज़रिए त्वरित जवाब',
  help_email:         'ईमेल करें',
  help_email_sub:     'seller-support@harvestconnect.in',
  help_guide:         '📖  विक्रेता गाइड और सर्वोत्तम प्रथाएं',
  help_guide_sub:     'मूल्य निर्धारण, फ़ोटोग्राफी और बिक्री बढ़ाने के टिप्स',
  help_faq_q1: 'नया ऑर्डर कैसे स्वीकार करें?',
  help_faq_a1: 'ऑर्डर टैब पर जाएं। नए ऑर्डर "नया" के तहत सबसे ऊपर दिखाई देते हैं। ऑर्डर कार्ड पर टैप करें और "स्वीकार करें" दबाएं — ऑर्डर स्वीकृत में चला जाता है और खरीदार को सूचित किया जाता है।',
  help_faq_q2: 'मुझे भुगतान कब और कैसे मिलेगा?',
  help_faq_a2: 'डिलीवरी पुष्टि के बाद अगले कार्यदिवस (T+1) पर भुगतान किया जाता है। आपके पंजीकृत बैंक खाते में सीधे ट्रांसफर होता है। Analytics स्क्रीन में भुगतान ट्रैक कर सकते हैं।',
  help_faq_q3: 'उत्पाद कैसे जोड़ें या संपादित करें?',
  help_faq_a3: 'उत्पाद टैब पर जाएं। नई लिस्टिंग बनाने के लिए "＋ उत्पाद जोड़ें" टैप करें, या किसी भी उत्पाद पर टैप करके संपादित करें। कीमत, स्टॉक, छवियां और विवरण कभी भी अपडेट कर सकते हैं।',
  help_faq_q4: 'HarvestConnect कितना कमीशन लेता है?',
  help_faq_a4: 'HarvestConnect प्रत्येक सफलतापूर्वक डिलीवर ऑर्डर पर 7% कमीशन लेता है। आप ऑर्डर मूल्य का 93% कमाते हैं। भुगतान ट्रांसफर से पहले कमीशन काटा जाता है।',
  help_faq_q5: 'अपना स्टोर सत्यापित कैसे कराएं?',
  help_faq_a5: 'प्रोफ़ाइल → KYC और दस्तावेज़ के ज़रिए अपना FSSAI लाइसेंस नंबर और दस्तावेज़ अपलोड करें। हमारी अनुपालन टीम कार्यदिवसों पर 48 घंटों के भीतर समीक्षा करती है।',
  help_faq_q6: 'ऑर्डर रद्द या अस्वीकार कैसे करें?',
  help_faq_a6: 'नए (अस्वीकृत) ऑर्डर के लिए: ऑर्डर टैप करें और "अस्वीकार करें" दबाएं, फिर कारण दर्ज करें। स्वीकृत ऑर्डर जो पूरा नहीं हो सकता, उसके लिए सीधे सहायता से संपर्क करें।',
  help_faq_q7: 'डिलीवरी क्षेत्र कैसे अपडेट करें?',
  help_faq_a7: 'प्रोफ़ाइल → डिलीवरी क्षेत्र पर जाएं (या डिलीवरी कवरेज कार्ड में "संपादित करें ›" टैप करें)। जिन क्षेत्रों में सेवा दे सकते हैं उन्हें चुनें और सेव करें।',
  help_faq_q8: 'क्या मेरे पास कई स्टोर हो सकते हैं?',
  help_faq_a8: 'हां। स्टोर स्विचर खोलने के लिए किसी भी स्क्रीन के ऊपर स्टोर आइकन टैप करें। अतिरिक्त स्टोर बनाने के लिए "नया स्टोर बनाएं" टैप करें।',

  // Transaction history modal
  tx_title:             'लेनदेन इतिहास',
  tx_total_credited:    'कुल जमा',
  tx_total_debited:     'कुल निकासी',
  tx_net_balance:       'शुद्ध शेष',
  tx_filter_all:        'सभी',
  tx_filter_credits:    'जमा',
  tx_filter_debits:     'निकासी',
  tx_filter_commission: 'कमीशन',
  tx_empty_title:       'अभी तक कोई लेनदेन नहीं',
  tx_empty_all:         'पूर्ण ऑर्डर यहां क्रेडिट और कमीशन के रूप में दिखाई देंगे।',
  tx_empty_filter:      'कोई लेनदेन नहीं मिला।',
  tx_type_credit:       'जमा',
  tx_type_debit:        'निकासी',
  tx_type_commission:   'कमीशन',

  // Delivery zones modal
  zones_title:           'डिलीवरी क्षेत्र',
  zones_hint:            'वे सभी क्षेत्र चुनें जहाँ आप डिलीवरी कर सकते हैं। चयनित क्षेत्रों के बाहर के खरीदारों को आपकी लिस्टिंग नहीं दिखेगी।',
  zones_desc_mandal:     'आपके मंडल के आसपास के गांव और कस्बे',
  zones_desc_district:   'आपके जिले के सभी क्षेत्र',
  zones_desc_state:      'तेलंगाना और आंध्र प्रदेश में कहीं भी',
  zones_desc_national:   'कूरियर पार्टनर के ज़रिए पूरे भारत में डिलीवरी',
  zones_saving:          'सहेज रहे हैं…',
  zones_save_pre:        'सहेजें ·',
  zones_zone:            'क्षेत्र',
  zones_zones:           'क्षेत्र',

  // Edit store modal
  edit_store_title:        'स्टोर संपादित करें',
  edit_store_name:         'स्टोर का नाम',
  edit_store_name_ph:      'जैसे: देसी डेयरी आर्मूर',
  edit_store_desc:         'विवरण',
  edit_store_desc_ph:      'खरीदारों को अपने स्टोर, उत्पाद और कहानी के बारे में बताएं…',
  edit_store_location:     'स्थान',
  edit_store_location_ph:  'जैसे: निज़ामाबाद, तेलंगाना',
  edit_store_address:      'स्टोर का पता',
  edit_store_address_ph:   'गली, इलाका, लैंडमार्क — आपके स्टोर प्रोफाइल पर दिखेगा',
  edit_store_social:       'सोशल मीडिया हैंडल',
  edit_store_instagram:    'इंस्टाग्राम',
  edit_store_instagram_ph: 'yourhandle',
  edit_store_facebook:     'फेसबुक',
  edit_store_facebook_ph:  'facebook.com/yourpage',
  edit_store_whatsapp:     'व्हाट्सएप बिजनेस',
  edit_store_whatsapp_ph:  '+91 98765 43210',
  edit_store_website:      'वेबसाइट',
  edit_store_website_ph:   'https://yourwebsite.com',
  edit_store_youtube:      'यूट्यूब चैनल',
  edit_store_youtube_ph:   'youtube.com/@yourchannel',
  edit_store_type:         'स्टोर का प्रकार',
  edit_store_status:       'स्टोर की स्थिति',
  edit_store_live_desc:    'दिखाई दे रहा है · ऑर्डर स्वीकार कर रहा है',
  edit_store_offline_desc: 'खरीदारों से छिपा हुआ',
  edit_store_saving:       'सहेज रहे हैं…',
  edit_store_save:         'बदलाव सहेजें',

  // Bank account modal
  bank_title_add:        'बैंक खाता जोड़ें',
  bank_title_update:     'बैंक खाता अपडेट करें',
  bank_subtitle:         'भुगतान T+1 पर इस खाते में जमा होते हैं',
  bank_holder_name:      'खाताधारक का नाम',
  bank_holder_name_ph:   'बैंक रिकॉर्ड के अनुसार',
  bank_account_no:       'खाता नंबर',
  bank_account_no_ph:    'पूरा खाता नंबर दर्ज करें',
  bank_account_reenter:  'बदलने के लिए दोबारा दर्ज करें',
  bank_ifsc:             'IFSC कोड',
  bank_ifsc_ph:          'जैसे: HDFC0001234',
  bank_name:             'बैंक का नाम',
  bank_name_ph:          'जैसे: HDFC बैंक',
  bank_upi:              'UPI ID',
  bank_upi_hint:         'वैकल्पिक — तेज़ निपटान के लिए',
  bank_upi_ph:           'जैसे: name@hdfcbank',
  bank_save_btn:         'खाता सहेजें',
  bank_update_btn:       'खाता अपडेट करें',
  bank_err_holder:       'खाताधारक का नाम आवश्यक है',
  bank_err_account:      'खाता नंबर 9–18 अंकों का होना चाहिए',
  bank_err_ifsc:         'अमान्य IFSC कोड (जैसे: HDFC0001234)',
  bank_err_bank_name:    'बैंक का नाम आवश्यक है',
  bank_err_save:         'सहेजने में विफल। कृपया फिर से प्रयास करें।',

  // KYC & documents modal
  kyc_title:             'KYC और दस्तावेज़',
  kyc_verified_title:    'KYC सत्यापित',
  kyc_pending_title:     'सत्यापन लंबित',
  kyc_verified_sub:      'आपका खाता सत्यापित है और भुगतान के लिए पूरी तरह से पात्र है।',
  kyc_pending_sub:       'अपना FSSAI नंबर और सहायक दस्तावेज़ जमा करें। व्यवस्थापक 48 घंटों में समीक्षा करते हैं।',
  kyc_fssai_label:       'FSSAI लाइसेंस नंबर',
  kyc_fssai_hint:        'आपके FSSAI खाद्य लाइसेंस प्रमाण पत्र से 14 अंकों का नंबर',
  kyc_docs_label:        'सहायक दस्तावेज़',
  kyc_no_docs:           'अभी तक कोई दस्तावेज़ अपलोड नहीं किया',
  kyc_doc_url_ph:        'दस्तावेज़ URL पेस्ट करें (Google Drive, Dropbox…)',
  kyc_doc_add:           'जोड़ें',
  kyc_upload_hint:       'कैमरा और गैलरी अपलोड जल्द आ रहा है। अभी के लिए, अपने दस्तावेज़ को Google Drive या Dropbox पर होस्ट करें और ऊपर शेयर करने योग्य लिंक पेस्ट करें।',
  kyc_accepted_title:    'स्वीकृत दस्तावेज़',
  kyc_accepted_1:        'आधार कार्ड (दोनों तरफ)',
  kyc_accepted_2:        'पैन कार्ड',
  kyc_accepted_3:        'FSSAI लाइसेंस प्रमाण पत्र',
  kyc_accepted_4:        'बैंक खाता विवरण / पासबुक',
  kyc_accepted_5:        'जीएसटी प्रमाण पत्र (यदि लागू हो)',
  kyc_saving:            'सहेज रहे हैं…',
  kyc_save:              'सहेजें',

  // Promotions modal
  promo_title:           'प्रमोशन और ऑफर',
  promo_new_form_title:  'नया प्रमोशन',
  promo_type_label:      'प्रमोशन का प्रकार',
  promo_type_percent:    '% छूट',
  promo_type_flat:       'फ्लैट ₹ छूट',
  promo_type_free_del:   'मुफ़्त डिलीवरी',
  promo_disc_pct:        'छूट प्रतिशत *',
  promo_disc_flat:       'छूट राशि *',
  promo_min_order:       'न्यूनतम ऑर्डर राशि (वैकल्पिक)',
  promo_valid_for:       'वैध अवधि',
  promo_days:            'दिन',
  promo_1_month:         '1 महीना',
  promo_create:          'बनाएं',
  promo_new_btn:         'नया प्रमोशन बनाएं',
  promo_new_sub:         'छूट, मुफ्त डिलीवरी, और बहुत कुछ',
  promo_empty_title:     'कोई सक्रिय प्रमोशन नहीं',
  promo_empty_sub:       'अधिक खरीदारों को आकर्षित करने और अपनी बिक्री बढ़ाने के लिए छूट या ऑफर बनाएं।',
  promo_min_order_label: 'न्यूनतम ऑर्डर ₹',
  promo_valid_pre:       'वैध',
  promo_active:          'सक्रिय',
  promo_paused:          'रोका गया',
  promo_pause:           'रोकें',
  promo_resume:          'फिर शुरू करें',
  promo_delete:          'हटाएं',
  promo_off:             'छूट',
  promo_created_toast:   'प्रमोशन बनाया गया!',
  promo_removed_toast:   'प्रमोशन हटाया गया।',
  promo_sync_note:       'प्रमोशन अभी के लिए केवल सत्र तक हैं। प्रमोशन सेवा लाइव होने पर स्थायी प्रबंधन उपलब्ध होगा।',

  // Kirana business model toggle
  create_store_business_model:    'व्यापार मॉडल',
  create_store_retail:            'खुदरा',
  create_store_retail_sub:        'उपभोक्ताओं को बेचता है',
  create_store_wholesale:         'थोक',
  create_store_wholesale_sub:     'दुकानों / पुनर्विक्रेताओं को थोक',

  // Custom delivery area (create-store)
  create_store_custom_area_on:    '✕ कस्टम क्षेत्र',
  create_store_custom_area_off:   '+ कस्टम क्षेत्र',
  create_store_custom_area_title: 'कस्टम डिलीवरी क्षेत्र चुना गया',
  create_store_custom_area_desc:  'स्टोर बनाने के बाद स्टोर सेटिंग्स से विशिष्ट मंडल, जिले, पिनकोड और राज्य परिभाषित कर सकते हैं।',

  // Duplicate store type warning
  create_store_dup_title_prefix:  'आपके पास पहले से एक',
  create_store_dup_title_suffix:  'स्टोर है',
  create_store_dup_desc:          'एक और बनाना अनुमत है, लेकिन अपने मौजूदा स्टोर का उपयोग करने पर विचार करें। क्या आप सुनिश्चित हैं?',
  create_store_dup_confirm:       'फिर भी बनाएं',

  // Product form — new fields
  product_form_moq_label:         'न्यूनतम ऑर्डर मात्रा (MOQ)',
  product_form_custom_area:       'कस्टम क्षेत्र',
  product_form_custom_area_title: 'कस्टम डिलीवरी क्षेत्र',
  product_form_custom_area_desc:  'आपके स्टोर के कस्टम डिलीवरी क्षेत्र में भेजता है',
};

const STRINGS: Record<Language, typeof EN> = { en: EN, te: TE, hi: HI };

interface LanguageContextValue {
  language:    Language;
  setLanguage: (lang: Language) => void;
  t:           (key: keyof typeof EN) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    AsyncStorage.getItem(STORAGE_KEY).then(stored => {
      if (stored === 'en' || stored === 'te' || stored === 'hi') setLanguageState(stored);
    });
  }, []);

  function setLanguage(lang: Language) {
    setLanguageState(lang);
    AsyncStorage.setItem(STORAGE_KEY, lang);
  }

  function t(key: keyof typeof EN): string {
    return STRINGS[language][key] ?? STRINGS.en[key] ?? key;
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used inside LanguageProvider');
  return ctx;
}
